### ISSUE TITLE
ISBAT see Shape Divider block styles in the correct orientation

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#1043]
**Describe the bug**
As a user, I should be able see the Shape Divider block properly oriented in its present state within the block’s Styles panel. 

**Screenshots**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/67250647-2f476780-f43a-11e9-961d-21a97b10d3cd.gif)

**Expected behavior**
The block within the preview properly shows its orientation based on the orientation toolbar controls. 

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.2.4

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any) 6.4+

**Comment by paranoia1906** [comment]
@richtabor 
![ShapeDividerExamplesMatching](https://user-images.githubusercontent.com/30462574/67519601-fd155000-f65b-11e9-8232-c18549c001e6.gif)
If the example is removed from Shape Divider block than the styles perform as expected. Get a look at this thread where this behavior was previously discovered.
https://godaddy.slack.com/archives/GKQGZCGK1/p1571079960161300?thread_ts=1571076610.158900&cid=GKQGZCGK1 

We may need to consider how to approach this issue lest we forgo the example/block preview.

![image](https://user-images.githubusercontent.com/30462574/67519990-d60b4e00-f65c-11e9-9e56-a9bce2a0d077.png)

**Comment by richtabor** [comment]
> @richtabor
> ![ShapeDividerExamplesMatching](https://user-images.githubusercontent.com/30462574/67519601-fd155000-f65b-11e9-8232-c18549c001e6.gif)
> If the example is removed from Shape Divider block than the styles perform as expected. Get a look at this thread where this behavior was previously discovered.
> https://godaddy.slack.com/archives/GKQGZCGK1/p1571079960161300?thread_ts=1571076610.158900&cid=GKQGZCGK1
> 
> We may need to consider how to approach this issue lest we forgo the example/block preview.
> 
> ![image](https://user-images.githubusercontent.com/30462574/67519990-d60b4e00-f65c-11e9-9e56-a9bce2a0d077.png)

Let's remove the block example for now 🤘
