### ISSUE TITLE
Add vw and vh units to Block inspector

### ISSUE THREAD

**Issue by sweetappleuk** [godaddy/coblocks#1054]
For more responsive layouts, being able to specify margin/padding in vh or vw units, as well as the current px, em and %, would be very helpful.

Adding  them to the const unitSizes = [] array appears to work with very easily...

/src/components/dimensions-control/index.js

const unitSizes = [
			//Append these...
			{
				name: _x( 'VH', 'A size unit for CSS markup', 'coblocks' ),
				unitValue: 'vh',
			},
			{
				name: _x( 'VW', 'A size unit for CSS markup', 'coblocks' ),
				unitValue: 'vw',
			},
		];

**Comment by richtabor** [comment]
Perhaps a better solution would be to introduce a filter to select which units to show here, instead of placing all of them here (though that may be another issue).

**Comment by richtabor** [comment]
I'm hesitant on complicating the interface by adding more visible top-level controls as such. Perhaps we need to tweak this interaction to better allow multi-selection. Maybe a select control?

**Comment by sweetappleuk** [comment]
The UI is already hugely complicated for someone that's isn't technical enough to understand the existing PX,EM,%, units controls. Physically there is room in the layout, so unless there's a plan to explicitly add additional controls in that area, I don't see an issue?

Alternatively, add a free text field for top/bottom/left/right field to allow people to enter, for example, 3rem 6vw 2rem 6vw. That would allow more Developer focused editors as much flexibility as they need, all the while whilst being hidden from non-techies who just use the simple Small/medium/Large/Huge settings.

**Comment by richtabor** [comment]
> The UI is already hugely complicated for someone that's isn't technical enough to understand the existing PX,EM,%, units controls.

That's reason enough to figure out how we could improve this particular control.
