### ISSUE TITLE
Coblocks plugin changes alignment on Luxury theme left menu

### ISSUE THREAD

**Issue by desnum** [godaddy/coblocks#1061]
**Describe the bug**
When the coblocks plugin is activated, the left menu gets pushed all the way to the left, rather than sitting closer to the logo as it is in the [Luxury theme demo](https://wordpress.com/theme/luxury/setup). 

**To Reproduce**
1. Activate the Luxury theme 
2. Set a left menu and a right menu
3. Activate the Coblocks plugin
4. Check the alignment of the left menu

**Screenshots**
With Coblocks activated:
![with](https://snipboard.io/louJ6i.jpg)

With Coblocks deactivated:
![without](https://snipboard.io/qTZ7Xn.jpg)

**Expected behavior**
The Coblocks plugin wouldn't impact menu layout. 

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [ ] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
Version 5.2.4

**Gutenberg Version**
What version of the Gutenberg plugin are you using? 
Version 6.7.0

Zen-2440778

**Comment by edequalsawesome** [comment]
The issue appears to be due to a conflict between the `.columns` `display: flex;` styling present in CoBlocks and the `.columns` class that's used in the header of the Luxury theme -- using this CSS in the Customizer for the site fixed the issue on my test site:

```
/* resolve issues with site navigation and coblocks */
@media only screen and (min-width: 768px) {
    #header .columns.nav-left,
    #header .columns.nav-right {
        display: block;
    }
}
```

**Comment by bishless** [comment]
See #1033 

I'm wondering why a non-scoped `.columns` rule exists in this plugin's stylesheet (see: [_columns.scss](https://github.com/godaddy/coblocks/blob/1b8d91f15f27bad3fbc3f12d3ab4a69e631fffc8/src/styles/style/_columns.scss)). Seems like it should be scoped only to its own blocks.

**Comment by richtabor** [comment]
We're leaning towards a utility-first approach with blocks that reuse common styling. I think we should tweak the `.columns` class to be a bit more unique as to prevent conflicts like this.

**Comment by paranoia1906** [comment]
Is likely resolved with https://github.com/godaddy/coblocks/pull/1035
