### ISSUE TITLE
ISBAT use Dynamic HR block with TwentyTwenty theme

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy/coblocks#1063]
**Describe the bug**
Running TwentyTwenty on WP 5.3 RC2 the Dynamic HR block does not render correctly on the published page.

**To Reproduce**

1. Add Dynamic HR block.
2. Publish page and view as user.
3. See error

**Screenshots**
**Dynamic HR in editor**
![image](https://user-images.githubusercontent.com/30462574/67409182-12608080-f56f-11e9-908c-f001132ced68.png)

**Dynamic HR on published page**
![image](https://user-images.githubusercontent.com/30462574/67409230-24daba00-f56f-11e9-8d70-56fe82347d52.png)

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.3 RC2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A

**Comment by paranoia1906** [comment]
Three additions to TwentyTwenty style.css are causing this unexpected behavior. Looking for advice on overriding. 

https://github.com/WordPress/twentytwenty/blob/f257dfff755c415dadc56a2c70a412421f39aad7/style.css#L427

https://github.com/WordPress/twentytwenty/blob/f257dfff755c415dadc56a2c70a412421f39aad7/style.css#L444

https://github.com/WordPress/twentytwenty/blob/f257dfff755c415dadc56a2c70a412421f39aad7/style.css#L439

When these lines are commented out, the block renders correctly.
