### ISSUE TITLE
Homepage Featured Content Slider in Purpose Theme broken when CoBlocks activated

### ISSUE THREAD

**Issue by trebor74** [godaddy/coblocks#1088]
Homepage Featured Content Slider in Purpose theme on Word Press does not work following latest update
**To Reproduce**

1. Choose Purpose theme. and CoBlocks
2. Set up a Home page content slider
3. Slider does not display and is black.

This also affects the coblocks/media-card layout and is now not displayed correctly

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [x ] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.4

**Gutenberg Version**
6.8.0

**Comment by richtabor** [comment]
Hey @trebor74, is Purpose a theme on .org or elsewhere? Could you provide a link where you're seeing the issue? 

Thanks!

**Comment by trebor74** [comment]
Hi, My web site url is https://trebornoslit74.wpcomstaging.com/ . When I switch CoBlocks on the slider disappears which is I have set it to now. Purpose is a Word Press business theme I am using . See ([https://wordpress.com/theme/purpose](https://wordpress.com/theme/purpose)) . The attached files show the issue.
![SwitchedOff](https://user-images.githubusercontent.com/4788301/68150553-df879680-ff37-11e9-8f40-af7853eb2fe5.PNG)

![SwitchedOn](https://user-images.githubusercontent.com/4788301/68150560-e3b3b400-ff37-11e9-90a5-5ffc1c89b720.PNG)

This was working fine. Word press have advised to wait for your update for a fix.

Thanks

Rob

**Comment by richtabor** [comment]
Thanks Rob. We actually fixed this [a couple days ago](https://github.com/godaddy/coblocks/pull/1035) and we're preparing a release to push out shortly. 

I appreciate you letting us know about it!
