### ISSUE TITLE
L10n: How will the new JSON system work with standalone installs?

### ISSUE THREAD

**Issue by kwight** [godaddy/coblocks#1092]
#1073 introduced a JSON-based system for managing CoBlocks localization. The plugin seems to be opted-in to language packs – how does this affect (if at all) the `translate.wordpress.org` language packs going forward?

There's mention in the diff of "translation automation", but I'm not sure how that fits in to it all. Is there a way for developers, working locally, to generate `mo` files (`json2po`?), or otherwise work with translations?

Thanks!

cc/ @fjarrett

**Comment by fjarrett** [comment]
Hey @kwight 👋 In short: No, this won't affect GlotPress, and that will still be the place to contribute to CoBlocks strings.

The JSON-based system we are using here on is strictly for our internal translation team's automation. They will pull in changes from `languages/coblocks.json` (which we generate from a POT file) and then deliver back `languages/{locale}.json` files. We then have more automation that will trigger `npm run json2po` and send PO files over to `translate.wordpress.org` where they will be vetted by native speakers. And eventually, our hope is to gain auto-approval again for strings via CLPTE.

If you are working locally and want to try out some translations just to see what they would look like, you would have to make your own changes to a `{locale}.json` file, then use `npm run json2po && npm run po2mo && npm run po2jed` to morph those into readable formats for WP and they should be picked up automatically (just make sure you don't have anything inside `wp-content/languages/plugins/coblocks*`.

Does this help?

**Comment by kwight** [comment]
@fjarrett Ah, great – good to hear that language packs will be unaffected. Thanks for the details, that helps a lot, much appreciated 👍
