### ISSUE TITLE
Posts block generating errors in wp-admin and frontend

### ISSUE THREAD

**Issue by bishless** [godaddy/coblocks#1120]
**Describe the bug**
When a Posts block is on a page or post, the display of the block seems broken and PHP notices get displayed in the editor as well as the frontend of the site. 

```
Notice:  Undefined index: postsToShow in /Users/dbishop/Sites/blue/wp-content/plugins/coblocks/src/blocks/posts/index.php on line 20

Notice:  Undefined index: order in /Users/dbishop/Sites/blue/wp-content/plugins/coblocks/src/blocks/posts/index.php on line 22

Notice:  Undefined index: orderBy in /Users/dbishop/Sites/blue/wp-content/plugins/coblocks/src/blocks/posts/index.php on line 23

Notice:  Undefined index: postFeedType in /Users/dbishop/Sites/blue/wp-content/plugins/coblocks/src/blocks/posts/index.php on line 34
```

The errors no longer display when I remove the Posts block from the page and update the page.

**To Reproduce**

1. Edit an existing Page.
2. Add the Posts block to the page from CoBlocks.
3. Errors occur

**Screenshots**
![on vanilla WP w/ Twenty Nineteen theme](https://user-images.githubusercontent.com/170618/68691143-7b189880-0530-11ea-90ec-8005cdff2713.png)

![on one of my production site's frontpage](https://user-images.githubusercontent.com/170618/68691366-de0a2f80-0530-11ea-9088-add2b4d605bb.png)

**Expected behavior**
I expected the Posts block to display properly and not generate errors.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.4

**Gutenberg Version**
6.8

**CoBlocks Version**
1.17

**Comment by jrtashjian** [comment]
Closed via #1121
