### ISSUE TITLE
Posts block 'Stacked' style isn't rendering as columns on frontend

### ISSUE THREAD

**Issue by bishless** [godaddy/coblocks#1129]
**Describe the bug**
When I add a Posts block and use the default 'Stacked' style, it looks as expected (a grid) in the editor, but does not look the same on the frontend. It seems that certain CSS classes are not output on the front end.

**To Reproduce**

1. Edit a Page.
2. Add a Posts block to the page. Set it to display 4 posts in 2 columns.
3. Click Update to save the page.
4. View the published page and you'll find all 4 posts displaying in a succession... not in a grid as expected.

**Screenshots**
[Video of behavior](https://cloudup.com/crZZUMgvCHa)

[Screenshots of the inspector](https://cloudup.com/chE2kjEgVjc) ... The first shot is the CSS classes that are included for the block when in the editor. The second, smaller image is from the frontend.

**Expected behavior**
I expected the Posts block to look similar on the frontend and in the editor.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.3

**Gutenberg Version**
6.8 and 6.9

**CoBlocks Version**
1.17.1

**Comment by richtabor** [comment]
#1127 may resolve this. Mind looking into this @AnthonyLedesma?
