### ISSUE TITLE
Posts horizontal style: Block error when changing column count from 1 to 2

### ISSUE THREAD

**Issue by broken8** [godaddy/coblocks#1130]
The Posts block in single-column horizontal style works as expected in the editor, but if 2 columns is selected the block throws an error. Saving the page and reloading the editor will display the block as intended - now with two columns - but clicking on the block throws the error again. 

**Note**: Front-end rendering is always good.

**To Reproduce**
1. In the Posts block select Style Horizontal. The block behaves as expected.
2. Select Columns - 2
3. Error.
4. Save the page
5. Reload the block editor
6. The block is now correctly displayed with 2 columns
7. Click on the block
8. Error.

**Screenshots**
![post-block-list-view+error](https://user-images.githubusercontent.com/38085966/68811930-bbc7fd00-0669-11ea-8e8a-586d60be0ff4.gif)

**Expected behavior**
Selecting more than one column should continue to display a representation of the block as selected.

**Isolating the problem:**
Mark completed items with an [x].

-   [ x ] This bug happens with no other plugins activated
-   [ x ] This bug happens with a default WordPress theme active
-   [ n/a ] This bug happens **without** the Gutenberg plugin active
-   [ x ] I can reproduce this bug consistently using the steps above

**Test Environment**
WP 5.3 + Twenty-Twenty, Tabor, Twenty-Nineteen

I get a react error in the console generated by WP on error - log attached.
[localhost-1573688250573.log](https://github.com/godaddy/coblocks/files/3843932/localhost-1573688250573.log)

If I can find a fix I'll raise a PR.

**Comment by broken8** [comment]
Looks like #1131 fixes this issue. My testing says yes!

Spent 2 hours on this last night, no joy!! The fix - so simple - and very helpful, thanks. Do I close this issue or you guys?

**Comment by EvanHerman** [comment]
@broken8 This issue will close when #1131 is merged, since we've referenced it in the comment for that PR. No need to manually close this.
