### ISSUE TITLE
ISBAT see Author block image accurately in the editor

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy/coblocks#1136]
**Describe the bug**
Author Block image is rendering strangely when in editor. This is repeatable on all themes and with the latest changes on master branch. This only occurs when using an image which is not equal dimensions width and height. Square images render correctly. All images seem to render correctly on published page.

**To Reproduce**

1. Add Author block.
2. Click on image placeholder and upload image to block.
  - (Must be non-square image to replicate.)
3. See error

**Screenshots**
**Non-square images do not render correctly.**
![authorImageRenderBug](https://user-images.githubusercontent.com/30462574/68972775-cc7f8c80-07a9-11ea-8fc4-0600f5e65a7e.gif)

**Square images render correctly.**
![image](https://user-images.githubusercontent.com/30462574/68972878-0e103780-07aa-11ea-86bb-324dff964a6e.png)

**Expected behavior**
Expect editor to reflect the same as published page.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A ( also happens with 6.9 running)

**Comment by fjarrett** [comment]
Confirmed. Happening for me as well.
