### ISSUE TITLE
Full width Row Block issue with Wide

### ISSUE THREAD

**Issue by phpbits** [godaddy/coblocks#365]
Adding here to make sure I won't forget :)

**Comment by phpbits** [comment]
<img width="1122" alt="screen shot 2019-02-25 at 10 57 37 pm" src="https://user-images.githubusercontent.com/3365507/53346028-248f0e00-3951-11e9-83d6-f322dc9426df.png">

**Comment by richtabor** [comment]
Is this an issue on TwentyNineteen, or Gutenberg without any editor styles?

**Comment by richtabor** [comment]
> Is this an issue on TwentyNineteen, or Gutenberg without any editor styles?

@phpbits Do you have more insight on this?

**Comment by phpbits** [comment]
@richtabor It's theme dependent I think. It's the difference of widths if you try more than one column the do the same but inside a one column row. I'm using CoBlocks theme.

**Comment by phpbits** [comment]
@richtabor Is it okay to close this now? Seems to be dependent on theme's wide width. Thanks!

**Comment by richtabor** [comment]
> @richtabor Is it okay to close this now? Seems to be dependent on theme's wide width. Thanks!

I'll double-check again and see if we're still getting issues.
