### ISSUE TITLE
Add ability to vertically align all the columns 

### ISSUE THREAD

**Issue by phpbits** [godaddy/coblocks#374]

**Comment by hacknug** [comment]
https://github.com/WordPress/gutenberg/pull/13899

**Comment by getdave** [comment]
@phpbits As @hacknug confirmed this is about to land.

**Comment by richtabor** [comment]
I'd like to add the same functionality to our Row block as well. 💪

**Comment by getdave** [comment]
@richtabor Luckily for you I've created the `BlockVerticalAlignmentToolbar` which will allow you to add this fairly easily.

**Comment by richtabor** [comment]
Here's how it's added to the Media & Text block within core: https://github.com/WordPress/gutenberg/pull/13989

**Comment by richtabor** [comment]
And here's where it's added to the columns block: https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/columns
