### ISSUE TITLE
Row block inherit colors are overriding theme styling

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#398]
We originally added in inherit styling to fix how TwentyNineteen had forced styling based on background color selections, but it seems to be fixed now. 

[Here's a CodePen example](https://codepen.io/colinaut/pen/pYaYwZ) demonstrating the overriding behavior.

**Comment by richtabor** [comment]
@phpbits Please test this with the following themes and let me know the results: 
- [ ] TwentyNineteen
- [ ] CoBlocks
- [ ] A "Gutenberg Unfriendly" theme (such as SoHo Lite from .org)

**Comment by phpbits** [comment]
CoBlocks theme : Heading and link color issue :

<img width="1219" alt="Screen Shot 2019-03-26 at 1 14 56 PM" src="https://user-images.githubusercontent.com/3365507/54973041-3b189b80-4fc9-11e9-908b-44badfdbd60e.png">

**Comment by phpbits** [comment]
@richtabor Same issue with SoHo lite but in front-end only

<img width="682" alt="Screen Shot 2019-03-26 at 1 18 19 PM" src="https://user-images.githubusercontent.com/3365507/54973164-ad897b80-4fc9-11e9-8159-f34d50f8e9bd.png">

**Comment by richtabor** [comment]
Relevant ticket on .org: https://wordpress.org/support/topic/css-issue-71/

**Comment by richtabor** [comment]
Another ticket on .org: https://wordpress.org/support/topic/obsolete-css-rules

**Comment by paranoia1906** [comment]
Another report in wp.org

https://wordpress.org/support/topic/text-color-in-column-issue/
