### ISSUE TITLE
Row block columns jump around when dragging to resize

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#399]
I've noticed that in Gutenberg 5.2, the resizing the row block causes the columns to jump around. I've recorded screenshots of TwentyNineteen, a Gutenberg unfriendly theme (basically a theme without editor styles) and our CoBlocks theme. It's occurring on each of them, and also when the Inspector RangeControl is used to resize. 

**TwentyNineteen theme:**
![twnetynineteen](https://user-images.githubusercontent.com/1813435/54687925-1ddc5c80-4af3-11e9-8c40-4c4fa263924e.gif)

**Gutenberg Unfriendly theme:** 
![unfriendly](https://user-images.githubusercontent.com/1813435/54687932-1fa62000-4af3-11e9-9a64-2bed169a96a8.gif)

**CoBlocks theme:** 
![coblocks](https://user-images.githubusercontent.com/1813435/54687939-20d74d00-4af3-11e9-85a8-70d1afdfab1e.gif)

**Comment by richtabor** [comment]
Related: https://github.com/coblocks/coblocks/issues/266 - but in that issue, TwentyNineteen is performing as expected.

**Comment by phpbits** [comment]
@richtabor There seems to be a jump regardless of the theme, it's probably depends on how fast `setAttributes` and `updateBlockAttributes` takes place : https://github.com/coblocks/coblocks/blob/ad39edac8e21b8229e73dedf59847e988ea743e1/src/blocks/row/column/components/edit.js#L223

Not sure what's the good idea on how to make it faster right now, let me know if you have better idea. Thanks!
