### ISSUE TITLE
ISBAT use the core Block Manager if its available

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#400]
We need to figure out a way to check for the core Block Manager and turn ours off if it's present.

I don't want to remove it entirely (yet), as some folks are likely not using Gutenberg 5.3 and may not update to WordPress 5.2 (where the Block Manager be included in core). 

@phpbits Is there also a way to perhaps migrate the selected blocks from our manager to core's?

**Comment by phpbits** [comment]
@richtabor Created deprecation on `remove/block-manager` branch 👍

**Comment by phpbits** [comment]
Forgot to tag, here's the commit : https://github.com/coblocks/coblocks/commit/0e39575bfa514ba07814140c22ad0bf38d4ee5c2

**Comment by phpbits** [comment]
For future reference : https://github.com/WordPress/gutenberg/issues/14139#issuecomment-480261866

**Comment by phpbits** [comment]
@richtabor Added the conditional deprecation so we won't have any issues with core WordPress Gutenberg version vs plugin repo 💯
