### ISSUE TITLE
Should we add typography controls to the Banner block?

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#453]
As we're not using InnerBlocks for the heading and paragraph components of the Banner block, we'll need to figure out the best way to have typography controls for the heading (and paragraph?). Thoughts @phpbits?

**Comment by phpbits** [comment]
@richtabor Added but still depends on the theme styling, I'm hesitant to add inherit font family for the heading. Let me know your thoughts. Thanks!
