### ISSUE TITLE
Resizablebox handle is out of place when a video is added to the Hero Block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#481]
See screen recording:
![ScreenFlow](https://user-images.githubusercontent.com/1813435/55673146-d6372e00-5871-11e9-92e7-6421bc4dd224.gif)

**Comment by phpbits** [comment]
@richtabor Suddenly I'm getting this issue with Hero Block. Can you verify that this isn't happening on your end? Thanks!

<img width="1396" alt="Screen Shot 2019-04-08 at 7 42 35 PM" src="https://user-images.githubusercontent.com/3365507/55721710-a1c09f00-5a36-11e9-8f35-930fbd5d55f8.png">

**Comment by phpbits** [comment]
@richtabor Fixes on `fix/hero-block-resizable` branch 👍
