### ISSUE TITLE
Video Background + Background Opacity is not functioning properly on the Row block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#483]
![ScreenFlow](https://user-images.githubusercontent.com/1813435/55673273-d33d3d00-5873-11e9-8bb5-aa31dd285ceb.gif)

**Comment by phpbits** [comment]
@richtabor Fixed on `fix/row-block-background` branch. Do I need to add another deprecated function? Thanks!

**Comment by richtabor** [comment]
> @richtabor Fixed on `fix/row-block-background` branch. Do I need to add another deprecated function? Thanks!

Is the markup changed on the save function? And when you switch to master + create a hero block with a video background, then switch to master, does the block break?

**Comment by phpbits** [comment]
@richtabor Yeah, I've moved the function that generate the video background : https://github.com/coblocks/coblocks/commit/3702c85c439c6c1152ed70e638f43467f32b4579

**Comment by richtabor** [comment]
@phpbits Yea then we'll need to add a deprecation.
