### ISSUE TITLE
Shape Divider ResizableBox handle should be aligned to the left

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#487]
Gutenberg 5.4 moved where the left ResizableBox handle displayed in the block. It should be aligned back to the left to prevent confusion of what's being dragged. 

<img width="1532" alt="Screen Shot 2019-04-16 at 9 48 33 AM" src="https://user-images.githubusercontent.com/1813435/56228521-d9c67400-602c-11e9-8fc0-d4c74be81c4d.png">

**Comment by daniel-matuszak** [comment]
#490
