### ISSUE TITLE
Inconsistencies with block insert UI elements 

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#488]
Currently the Accordion block and Row block have similar "Add block" UI elements, but both are styled differently. We need to update the Accordion block's "Add Accordion Item" styles to resemble the Row block's "+" UI (_background color, border-radius, border-color_). 

Current:
<img width="865" alt="Screen Shot 2019-04-16 at 2 47 31 PM" src="https://user-images.githubusercontent.com/1813435/56246331-97199180-6056-11e9-9a6d-c8e00880779c.png">

**Comment by daniel-matuszak** [comment]
#493
