### ISSUE TITLE
ISBAT have a simplified Google Map experience if I don't specify an API key

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/coblocks#495]
We could provide a subset of the experience if a person doesn't want to register for Google Maps (iframe the map directly).

**Comment by shivikathapar** [comment]
https://godaddy.invisionapp.com/share/YKRLQKEQEWR

Mocks attached here.

**Comment by shivikathapar** [comment]
Proposed change:
Remove Google API key option from block placeholder area and only make it available in the Settings Sidebar as a Panel.

ttps://godaddy.invisionapp.com/share/YKRLQKEQEWR

**Comment by jonathanbardo** [comment]
@richtabor This is 95% there I think. Let me know if you like the new behavior.
