### ISSUE TITLE
Refactor blocks to have save, deprecations, transforms and icons in their own directories

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#504]
As a developer, ISBAT clearly understand what is happening within each block, as blocks are written in a similar fashion as core Gutenberg. This would further align our blocks per the [Gutenberg Block Registration API RFC #13693](https://github.com/WordPress/gutenberg/blob/add/block-registration-rfc/docs/rfc/block-registration.md).

**Comment by richtabor** [comment]
The new stacked, masonry and carousel blocks are already done.

**Comment by paranoia1906** [comment]
#### Check-off Blocks when they are confirmed to be refactored either in present state or in a relevant pull request.
- [ ] Accordion Block
  * [ ] Accordion Item Block
- [ ] Alert Block
- [ ] Author Profile Block
- [ ] Buttons Block
- [ ] Carousel Gallery Block
- [ ] Click to Tweet Block
- [ ] Dynamic Separator Block
- [ ] Features Block
- [ ] Food & Drinks Block
  * [ ] Food Item Block
- [ ] Form Block
- [ ] Gif Block
- [ ] GitHub Gist Block
- [ ] Hero Block
- [ ] Highlight Block
- [ ] Icon Block
- [ ] Logos & Badges Block
- [ ] Map Block
- [ ] Masonry Gallery Block
- [ ] Media Card Block
- [ ] Pricing Table Block
- [ ] Resizable Row/Columns Blocks
- [ ] Services Block 
- [ ] Shape Divider Block
- [ ] Social Profiles Block 
- [ ] Social Sharing Block
- [ ] Stacked Gallery Block

**Comment by richtabor** [comment]
I think some of this refactoring has been done in #688 too.

**Comment by paranoia1906** [comment]
- Logos & Badges block is already refactored to match Gutenberg core structure.

**Comment by paranoia1906** [comment]
@richtabor All blocks should be refactored now. Many have separate pull requests but several have refactors committed to the `tweak/block-json` branch. This was done in attempt to avoid the majority of merge conflicts. 

https://github.com/godaddy/coblocks/pull/688

**Comment by jrtashjian** [comment]
Closed by #688
