### ISSUE TITLE
Bug: Hero block uneditable once saved

### ISSUE THREAD

**Issue by seb86** [godaddy/coblocks#511]
Once you have saved your post with the Hero Block you are not able to edit again due to an invalidation with the markup.

**Comment by richtabor** [comment]
@seb86 Could you list out a way to replicate the issue? And are you using master, or the plugin from .org? Thanks!

**Comment by seb86** [comment]
Sure @richtabor . I'm using the latest from .org and I simply just create a hero block, fill in what I want and save. While the content is saved and loading on the page, when comes to returning to edit the block it says...

> The block contains unexpected or invalid content.

**Comment by seb86** [comment]
This is what it shows when I press the resolve button.

![Screenshot_2019-04-22 Edit Page ‹ Sébastien Dumont — WordPress](https://user-images.githubusercontent.com/497406/56509930-96866c80-6528-11e9-8ce1-223aa0b78938.png)

**Comment by richtabor** [comment]
@seb86 Are you still getting this with the master here on GitHub?

**Comment by richtabor** [comment]
I'm unable to replicate this issue so I'm closing. Thanks!

**Comment by seb86** [comment]
@richtabor Seems to be OK now.

**Comment by seb86** [comment]
@richtabor It seems it is still broken.

I am using WordPress 5.2.1, CoBlocks 1.10.0 and EditorsKit 1.6.2

Here is a screen recording trying to edit a page with the Hero block. You will see that the only way to continue editing the block is by recovering it first which is not a great experience.

https://www.youtube.com/watch?v=-ZdmMUtQSEw

Maybe there is a plugin compatibility issue with EditorsKit. Maybe @phpbits can check the issue out too.

**Comment by seb86** [comment]
Also, when the block is recovered it resets the background color to default if it was cleared before and stops any previously set background image from loading.

**Comment by richtabor** [comment]
Hey @seb86, do you get this when EditorsKit is deactivated?

**Comment by seb86** [comment]
Just deactivated EditorsKit. Same results. :(

**Comment by richtabor** [comment]
Gutenberg plugin?

**Comment by seb86** [comment]
No I don't have the Gutenberg plugin installed.

**Comment by phpbits** [comment]
@seb86 and @richtabor Sorry for late response. Does activating Gutenberg fixes the issue? Thanks!

**Comment by seb86** [comment]
Same result with Gutenberg installed @phpbits and @richtabor

**Comment by paforson** [comment]
I'm having this same issue with coblocks often... once it happens the only way forward is to recreate the block. Trying to edit or recover the block does  ot work.

**Comment by phpbits** [comment]
@seb86 since you are also using EditorsKit would you mind updating to latest version and export the block that having this issue so that I can import that specific block on my end. Here's how the export works : https://twitter.com/phpbits/status/1138412218721026049 . Let me know how it goes. Thanks!

**Comment by seb86** [comment]
@phpbits Here you go.

```
{
  "__file": "core_block",
  "content": "<!-- wp:coblocks/hero {\"layout\":\"center-center\",\"fullscreen\":true,\"marginTop\":0,\"marginBottom\":0,\"marginTopTablet\":0,\"marginBottomTablet\":0,\"marginTopMobile\":0,\"marginBottomMobile\":0,\"backgroundImg\":\"https://cocart.xyz/wp-content/uploads/2019/06/w-349443-unsplash.jpg\",\"contentAlign\":\"center\",\"textColor\":\"dark-black\",\"maxWidth\":810,\"editorskit\":{\"id\":\"editorskit-5413527670\",\"devices\":false,\"desktop\":true,\"tablet\":true,\"mobile\":true,\"loggedin\":true,\"loggedout\":true,\"acf_visibility\":\"\",\"acf_field\":\"\",\"acf_condition\":\"\",\"acf_value\":\"\",\"migrated\":false},\"coblocks\":{\"id\":\"5413527663\"},\"noBottomMargin\":true,\"noTopMargin\":true} -->\n<div class=\"wp-block-coblocks-hero alignfull has-text-color has-dark-black-color coblocks-hero-5413527663 editorskit-5413527670 mb-0 mt-0\"><div class=\"wp-block-coblocks-hero__inner has-background-image bg-no-repeat bg-center-center bg-cover hero-center-center-align has-padding has-huge-padding has-center-content is-fullscreen\" style=\"background-image:url(https://cocart.xyz/wp-content/uploads/2019/06/w-349443-unsplash.jpg)\"><div class=\"wp-block-coblocks-hero__box\" style=\"max-width:810px\"><!-- wp:paragraph {\"textColor\":\"dark-black\",\"className\":\"has-huge-font-size\",\"editorskit\":{\"id\":\"editorskit-54133221133\",\"devices\":false,\"desktop\":true,\"tablet\":true,\"mobile\":true,\"loggedin\":true,\"loggedout\":true,\"acf_visibility\":\"\",\"acf_field\":\"\",\"acf_condition\":\"\",\"acf_value\":\"\",\"migrated\":false},\"fontFamily\":\"Helvetica\",\"letterSpacing\":-1,\"fontWeight\":\"bold\"} -->\n<p style=\"font-family:Helvetica;font-weight:bold;letter-spacing:-1px\" class=\"has-text-color has-dark-black-color has-huge-font-size editorskit-54133221133 has-custom-font has-custom-weight has-custom-letterspacing\">CoCart v2</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph {\"placeholder\":\"Add content...\",\"textColor\":\"dark-black\",\"customFontSize\":80,\"editorskit\":{\"id\":\"editorskit-5413527843\",\"devices\":false,\"desktop\":true,\"tablet\":true,\"mobile\":true,\"loggedin\":true,\"loggedout\":true,\"acf_visibility\":\"\",\"acf_field\":\"\",\"acf_condition\":\"\",\"acf_value\":\"\",\"migrated\":false},\"fontFamily\":\"Helvetica\",\"lineHeight\":1.05,\"letterSpacing\":-1,\"fontWeight\":\"bold\"} -->\n<p style=\"font-size:80px;line-height:1.05;font-family:Helvetica;font-weight:bold;letter-spacing:-1px\" class=\"has-text-color has-dark-black-color editorskit-5413527843 has-custom-size has-custom-font has-custom-weight has-custom-lineheight has-custom-letterspacing\"> A lot faster and more powerful options.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:paragraph {\"textColor\":\"dark-black\",\"editorskit\":{\"id\":\"editorskit-5413620403\",\"devices\":false,\"desktop\":true,\"tablet\":true,\"mobile\":true,\"loggedin\":true,\"loggedout\":true,\"acf_visibility\":\"\",\"acf_field\":\"\",\"acf_condition\":\"\",\"acf_value\":\"\",\"migrated\":false},\"fontFamily\":\"Helvetica\"} -->\n<p style=\"font-family:Helvetica\" class=\"has-text-color has-dark-black-color editorskit-5413620403 has-custom-font\">CoCart v2 introduces it's own namespace, major improvements to the API and new ways to return responses to reduce API requests in your app.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:button {\"backgroundColor\":\"dark-black\",\"textColor\":\"light-gray\"} -->\n<div class=\"wp-block-button\"><a class=\"wp-block-button__link has-text-color has-light-gray-color has-background has-dark-black-background-color\" href=\"https://cocart.xyz/cocart-v2-0-0-beta-1/\">Find out more</a></div>\n<!-- /wp:button --></div></div></div>\n<!-- /wp:coblocks/hero -->"
}
```

**Comment by phpbits** [comment]
@seb86 weird. I'm getting the console log on import but it's rendering fine after that. `createBlock` is probably fixing the issue automatically on my import functions. Since there's no error log it's pretty hard to pinpoint the issue. I'll let you know when I have something concrete. Thanks!
