### ISSUE TITLE
ISBAT remove all nested blocks within the Hero block

### ISSUE THREAD

**Issue by colorful-tones** [godaddy/coblocks#514]
A user can remove all the text and call-to-action areas from the Hero block and just have the image. However, if they save and then try to go back and Edit the content later then the text and calls-to-action area come back. Should they not notice this (because they came back to update something else in the content, then once they save the default text and calls-to-action are saved and output on the front end.

Steps to recreate:
1. Create a new Page and add Hero block
2. Remove all text and calls-to-action areas from within the Hero Block and Publish. 
3. Visit: `/wp-admin/edit.php?post_type=page` and find your newly created and published page, and click 'Edit'.
4. Notice the text and calls-to-action are back.
5. Click, 'Update' to update the post and then view the output on front end.

This could likely cause some confusion and degrade user experience.

Using CoBlocks 1.9.4 and WordPress 5.1.1. 

I'm not sure if this is possibly related to #511 ?

**Comment by richtabor** [comment]
I was able to replicate this issue. 🤔

**Comment by richtabor** [comment]
You can remove individual blocks, but if you remove all the nested blocks, the block re-adds the default TEMPLATE

**Comment by EvanHerman** [comment]
It doesn't seem as though I can remove the call to action buttons/links inside of the hero block.

**Comment by EvanHerman** [comment]
Looks like a limitation with the `InnerBlocks` component. Any component using `<InnerBlocks.Content />` in their save encounters this issue. This fix might have to come from WordPress core.

**Comment by onuro** [comment]
If I may, I use the same kind of approach on my plugin for Gutenberg for some of my parent blocks. Based on my UX experience, this is perfectly fine. If you define block templates for a block, removing that template and saving without any content causing re-ghosting the template is an end case for user. It's not a dead end. Which is fine :)

**Comment by richtabor** [comment]
Yea I think the same @onuro. 👍
