### ISSUE TITLE
Text Transform Normal

### ISSUE THREAD

**Issue by drivenfaroff** [godaddy/coblocks#516]
On the "Change typography" dropdown you are able to change the text transform. Several things are happening here when choosing the "Normal" option.

In the back end, setting this to "Normal" doesn't change the style, it will keep whatever was previously set. So if you first set "lowercase" and then change it to "normal", the style will still show "lowercase". However, it you go from "Default" to "Normal" it will add `data-custom-texttransform="1"` which has CSS of "text-transform: inherit" and will show correctly.

On the front end, the setting of "Normal" comes through as `text-transform: normal;`. This isn't valid syntax. To me the "Normal" option would probably be best set to "initial" or "inherit". So on the front and back end it would output `text-transform: initial;`.

![2019-05-08 14-39-47 2019-05-08 14_49_06](https://user-images.githubusercontent.com/1910216/57403977-80231680-71a0-11e9-868c-107e3ab73ac3.gif)

https://github.com/godaddy/coblocks/blob/dd86542a256a784ab38451c518a487f034df48f8/src/components/typography-controls/index.js#L131

**Comment by richtabor** [comment]
Good find Bryce!
