### ISSUE TITLE
Bug: Trying to get property 'ID' of non-object...

### ISSUE THREAD

**Issue by AlchemyUnited** [godaddy/coblocks#523]
Notice: Trying to get property 'ID' of non-object in /home/content/p3pnexwpnas02_data01/60/42477160/html/wp-content/plugins/coblocks/includes/class-coblocks-accordion-ie-support.php on line 82

This is happening on a WooComm archive (category) index page where there are no products with that category assigned.

**Comment by richtabor** [comment]
Thanks @AlchemyUnited, we have a fix #484 coming. Cheers!
