### ISSUE TITLE
ISBAT click video thumbnails on the Getting Started page and not redirect away from my site

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/coblocks#549]
On the '**Getting Started**' page, clicking on any of the video thumbnails redirects the user away from the page and over to YouTube. It would be great if these videos opened in a modal and kept the user on the same page.

### Example
![Example](https://user-images.githubusercontent.com/5321364/58210164-a1aef280-7cb6-11e9-8f05-86d4b1bb7138.png)

**Comment by richtabor** [comment]
@EvanHerman I believe we resolved this when we updated the build/deployment bits last week. 
![ScreenFlow](https://user-images.githubusercontent.com/1813435/58210719-2e0de500-7cb8-11e9-9d80-a0521ffaf850.gif)

**Comment by EvanHerman** [comment]
@richtabor Perfect - I missed that! 🥇
