### ISSUE TITLE
ISBAT understand what "Stacked" and "Masonry" blocks are

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#581]
Current it is not very clear that the "Stacked" and "Masonry" blocks are in fact gallery blocks. I should be able to clearly understand that they are types of galleries. 

I have two suggestions: 

**1.** Change the block names within the Block Inserter to add "Gallery" (Screenshot A). 

**2.** Move our gallery blocks (Masonry, Carousel and Stacked) into a new "Galleries" category within the block inserter. (Screenshot B). When a user searches for a gallery, the gallery blocks will be clearly labeled in the Gallery category.

**Screenshot A:**
<img width="619" alt="Screen Shot 2019-06-07 at 11 51 13 AM" src="https://user-images.githubusercontent.com/1813435/59127024-838ef680-8934-11e9-8a17-3b20493362d6.png">

**Screenshot B:**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/59125650-f5654100-8930-11e9-8ee1-72bbec12fd74.gif)

**Comment by richtabor** [comment]
The labels in Option 1 (changing block names) are quite long and can be skewed in other areas of the editor UI: 
<img width="712" alt="Screen Shot 2019-06-07 at 3 01 07 PM" src="https://user-images.githubusercontent.com/1813435/59127247-1891ef80-8935-11e9-8b55-14adefb1b7f7.png">

**Comment by gmays** [comment]
Both could work, I don't have a strong opinion either way.  Some thoughts/questions:

Is there a reason that only CoBlocks has the CoBlocks logo and not Gallery Blocks?  Could customers accidentally assume the Gallery Blocks are part of core and uninstall CoBlocks after assuming they're not using any other blocks?

Do we think this is scalable?  There will likely be other reasons to clarify names for future blocks.  Does this set a precedence for creating a new group every time?

How big a deal is it that the Block names are long?  I assume at some point in the long future of Gutenberg this will become the norm as we get more nuanced blocks and this will be solved a more elegant way (maybe we solve it).

**Comment by richtabor** [comment]
> Is there a reason that only CoBlocks has the CoBlocks logo and not Gallery Blocks? Could customers accidentally assume the Gallery Blocks are part of core and uninstall CoBlocks after assuming they're not using any other blocks?

We could have the CoBlocks logo on both categories. I think that's fine. 

> Do we think this is scalable? There will likely be other reasons to clarify names for future blocks. Does this set a precedence for creating a new group every time?

If there were a number of a specific classification of blocks (such as Gallery blocks, where we could very well have quite a few gallery blocks), having additional categories in the future is plausible.

> How big a deal is it that the Block names are long? I assume at some point in the long future of Gutenberg this will become the norm as we get more nuanced blocks and this will be solved a more elegant way (maybe we solve it).

It's not a big deal honestly. 👍

**Comment by aaroncampbell** [comment]
I don't think the two-line name is a big issue and shouldn't be a worry for future blocks, but in this particular case I lean toward the galleries category. I like how organized it is and I could easily see additional gallery blocks being added. I also like Gabe's note of having the logo added to the galleries category to make it easy to identify as coming from CoBlocks.

**Comment by fjarrett** [comment]
@richtabor If we do Option 2 I assume the core Gallery block won’t be included? So from the user’s perspective, it’s not a comprehensive set of all Galleries available, just _our_ Galleries?

**Comment by richtabor** [comment]
> @richtabor If we do Option 2 I assume the core Gallery block won’t be included? So from the user’s perspective, it’s not a comprehensive set of all Galleries available, just _our_ Galleries?

That's correct.

**Comment by richtabor** [comment]
Here is a recording of a "Gallery Blocks" category with the CoBlocks icon: 

![](https://user-images.githubusercontent.com/1813435/59166680-2d6bb000-8afa-11e9-98b6-a9ba7eeffa28.gif)

**Comment by richtabor** [comment]
Here's a screenshot of appending "Gallery" to the block names. Thoughts @fjarrett? 

![](https://user-images.githubusercontent.com/1813435/59462250-52f60380-8df1-11e9-8f9f-5ad90bd30a37.png)

**Comment by richtabor** [comment]
Resolved via #584.
