### ISSUE TITLE
Init JS frontend components when pjax page loads

### ISSUE THREAD

**Issue by lmartins** [godaddy/coblocks#588]
Hi, thank you for the great content blocks!

Is there a way to instantiate the components when you're loading pages with pjax?

**Comment by richtabor** [comment]
Hey @lmartins, do you mind clarifying a bit?

**Comment by lmartins** [comment]
@richtabor oh man, sorry about that. Re-reading that I realise who confusing I've phrased it.

I'm running a pjax library on this build to have animation and transitions between pages, and even though that library offers an API which I can use to manage lifecycle of my own components, I was wondering if there's any methods or events for coblocks that require JS I can plug into the same way?

Again, sorry for the vague question in the first place, and thank you for the awesome library!

**Comment by onuro** [comment]
I believe that's something related to the pjax library, not this plugin.

You just need to call the plugin script dependencies after page is ready state editing the pjax library's promise states.
