### ISSUE TITLE
ISBAT use the Heading block with Gutenberg 5.9

### ISSUE THREAD

**Issue by benjaminluoma** [godaddy/coblocks#589]
Hi Rich! Here's another issue with Gutenberg compatibility:
![image](https://user-images.githubusercontent.com/2529580/59384627-380b8c80-8d28-11e9-9260-7b8e193f0319.png)

Headings are getting wiped out. Looks like the h tags are getting striped right out:
![image](https://user-images.githubusercontent.com/2529580/59384775-8caf0780-8d28-11e9-8b89-2d672a23a426.png)

**Comment by onuro** [comment]
Yeah there're 2 things that are issues with 5.9 update:
1: Blocks using the Color Settings extension gets the trouble from ColorSettings() function. (TypeError: Cannot call a class as a function)
2: 5.9 is deprecating "**wp.editor**" and requiring "**wp.blockEditor**" to be used as a component base.

I couldn't find a solution myself when I tried a fix on the forked version of your plugin, but the #2 was easy to fix :)

**Comment by drivenfaroff** [comment]
I can confirm that this is happening with CoBlocks 1.10.0 and Gutenberg 5.9.0.

![coblocks-heading](https://user-images.githubusercontent.com/1910216/59442151-48227b00-8dbf-11e9-8264-e9b2e2a486ab.gif)

**Comment by richtabor** [comment]
PR #557 resolves this, but I don't like the idea of removing Color Settings for the Heading block before its added to core. I'll dig in a bit more though.

**Comment by richtabor** [comment]
PR #597 resolves this issue for the meantime until we merge #557 which removes the Color Settings from the Heading block altogether (as its added in the Gutenberg plugin now).
