### ISSUE TITLE
Add third-party support for the Typography Control Panel

### ISSUE THREAD

**Issue by phpbits** [godaddy/coblocks#59]
Use `CoBlocksTypography`

**Comment by richtabor** [comment]
We could name it `coBlocksTypography`

**Comment by richtabor** [comment]
Let's use a lowercas `c`: coBlocksTypography
> Use `CoBlocksTypography`

**Comment by seb86** [comment]
Would love to support my block with this. Happy to experiment while this is worked on.

**Comment by phpbits** [comment]
@richtabor Added here : https://github.com/thatplugincompany/coblocks/tree/coBlocksTypography-support 

```
supports: {
	coBlocksTypography: true,
},
```

**Comment by seb86** [comment]
What conditions can be used to hide inspector controls for typography in a 3rd party block if CoBlocks is installed?

**Comment by richtabor** [comment]
> What conditions can be used to hide inspector controls for typography in a 3rd party block if CoBlocks is installed?

I'm not quite following. Do you mean if another third-party typography system was installed?

**Comment by seb86** [comment]
Yes

**Comment by richtabor** [comment]
I don't know that we could put something in place to hide someone elses controls really.

**Comment by seb86** [comment]
For example, in my block I have a control that allows the overlay text to be normal or italic. If CoBlocks is installed and I support your typography system. I would like to be able to hide it.

**Comment by richtabor** [comment]
Ah, you mean you're third-party block.  👍 

You could probably use [hasBlockSupport](https://github.com/WordPress/gutenberg/blob/47736a4d25a7d69d83389ec1521458a57011907a/packages/editor/src/hooks/anchor.js#L37).

**Comment by richtabor** [comment]
We'll lean into this more after we release 2.0, but if you have any ideas how to implement that kind of check, let me know @seb86. It's definitely a good idea.

**Comment by seb86** [comment]
> 
> 
> We'll lean into this more after we release 2.0, but if you have any ideas how to implement that kind of check, let me know @seb86. It's definitely a good idea.

I will let you know what I come up with.

**Comment by richtabor** [comment]
@phpbits Could you test and confirm that this is working properly?

**Comment by phpbits** [comment]
@richtabor merged changes from master on `coBlocksTypography-support` and seems to be working perfectly :) 

https://github.com/coblocks/coblocks/issues/59#issuecomment-457200686

**Comment by richtabor** [comment]
> @richtabor merged changes from master on `coBlocksTypography-support` and seems to be working perfectly :)
> 
> [#59 (comment)](https://github.com/coblocks/coblocks/issues/59#issuecomment-457200686)

How did you test this @phpbits?

**Comment by phpbits** [comment]
@richtabor Just add the support to custom block w/o it. You could probably test it out on Block Gallery.
