### ISSUE TITLE
New Facebook branding icon for Social block

### ISSUE THREAD

**Issue by colorful-tones** [godaddy/coblocks#599]
**Is this enhancement related to a problem? Please describe.**
Facebook recently announced new branding guidelines with a new icon, which should be updated within the Social block (possibly others?).

https://en.facebookbrand.com/#brand-guidelines-assets

**Describe the solution you'd like**
Update the Facebook icon wherever used in CoBlocks please.

**Comment by richtabor** [comment]
Good call @colorful-tones. 

The `dist/images/social/facebook.svg` icon should be updated with the "[F-logo](https://en.facebookbrand.com/assets/f-logo/?audience=landing)".
