### ISSUE TITLE
Add option to move CoBlocks dashboard menu item to "Settings" or "Tools"

### ISSUE THREAD

**Issue by voneff** [godaddy/coblocks#603]
**Is your feature request related to a problem? Please describe.**
As of now, CoBlocks adds a top-level menu item in the WP dashboard. Apart from some basic onboarding info there is no real value there that would justify such an exposed position. As I understood from [this issue](https://github.com/godaddy/coblocks/issues/265), there might be more settings coming in the future. In any case and in order to unclutter the WP dash, I would love to see an option to move the CoBlocks menu item under the "Settings" or the  "Tools" menus.

**Describe the solution you'd like**
UI: Add a checkbox to move the CoBlocks Settings Page.

**Describe alternatives you've considered**
You could consider not adding a top-level menu item in the first place and rather adding a submenu item under "Settings" or "Tools" right away.

**Comment by richtabor** [comment]
I'm not sure about a checkbox somewhere, but perhaps a filter? 🤔

**Comment by voneff** [comment]
I got the idea with a checkbox from another plugin which was sitting front row at first and where I only had to set the setting once and was done with it forever... The plugin authors then added a checkbox, see screenshot from the menu:
![iubenda_submenu](https://user-images.githubusercontent.com/16760054/60115418-2be6ec80-9776-11e9-8707-191fb5dca8b6.png)

**Comment by voneff** [comment]
I moved the CoBlocks menu item now manually with [this quick snippet](https://gist.github.com/voneff/d0a1bf5a77b3f45b7bdeaa52996fa623) – but that might not be for everybody.

**Comment by EvanHerman** [comment]
@voneff We're merging in a change that introduces a filter to make this process easier.

https://github.com/godaddy/coblocks/pull/604

#### New Filter
`coblocks_getting_started_submenu_parent_slug `

#### Example Usage
```php
/**
 * Nest the CoBlocks Getting Started page inside the Tools admin menu
 *
 *
 */
function nest_coblocks_getting_started_menu_item( $parent_slug ) {

   return 'tools.php';

}
add_filter( 'coblocks_getting_started_submenu_parent_slug', 'nest_coblocks_getting_started_menu_item' );
```

The above example will nest the CoBlocks Getting Started menu item inside of the Tools menu.

Thanks for making the suggestion! 👍

**Comment by voneff** [comment]
@EvanHerman Great, you're welcome, thanks for picking this one up! I might have some more in the pipeline…

**Comment by paranoia1906** [comment]
Relevant support request on wp.org

https://wordpress.org/support/topic/top-level-wp-admin-menu-icon/
