### ISSUE TITLE
ISBAT quickly turn on/off icons in the Share block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#607]
**Is this enhancement related to a problem? Please describe.**
The Share block uses a number of toggles to turn on and off various icons. This breaks a Gutenberg design pattern that states that checkboxes should be used when folks want to select one, or multiple, items from a list ([source](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/checkbox-control#design-guidelines)). 

**Describe the solution you'd like**
The CheckBoxControl should be used instead of the current ToggleControl components for each icon. We should also move the selection list out of it's own panel and into the Share Settings panel, as it will take up much less room. This will make the selection process much easier and faster.

**Additional context**
The new icon selection list should remain at the bottom of the Share Settings PanelBody, even as the UI changes based on the style selected. 

**Screenshot**
![social-block-checkboxes](https://user-images.githubusercontent.com/1813435/60211824-e8e85000-982d-11e9-9128-25a93f85f3be.png)

**Comment by paranoia1906** [comment]
Making a pull to address this issue. Pull also partially addresses https://github.com/godaddy/coblocks/issues/504 as the block is refactored to Gutenberg recommended structure and uses block.json.

![image](https://user-images.githubusercontent.com/30462574/60292135-53060100-98d1-11e9-8162-e78244f1cd11.png)

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/612

**Comment by richtabor** [comment]
It's looking pretty good @paranoia1906. Just a couple bits of feedback. 

1. The list items need to have proper margin between each other (similar to my screenshot above, and the upcoming Food & Drinks/ Food Item block). `margin-bottom: 8px` did it for the Item Attributes checklist. Take a look at the menu block branch and replicate that margin and label margin as well. 

2. The text should simply read "Icons" instead of "Toggle the.."

**Comment by paranoia1906** [comment]
Added the styles that match the food-item block and changed text to 'icons'.

![image](https://user-images.githubusercontent.com/30462574/60359832-084abe80-998f-11e9-88b7-66ebfd709b5e.png)

**Comment by richtabor** [comment]
Closed by #612
