### ISSUE TITLE
ISNBAT save the Form fields blocks as reusable blocks

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#618]
**Describe the bug**
It's currently possible to save form fields as reusable blocks. This functionality is not necessary ,or useful, in this context - so we should opt out of it at the block level.

**To Reproduce**

1. Add a Form block
2. Select a field child block
3. Click on the vertical ... to open the panel
4. See "Add to Reusable blocks" listed

**Screenshots**
<img width="973" alt="Screen Shot 2019-06-28 at 12 13 57 PM" src="https://user-images.githubusercontent.com/1813435/60356159-40a5c900-999e-11e9-9426-4839055656ff.png">

**Expected behavior**
The option to set a field as a reusable block is not present, using the following: 

```
supports: {
	reusable: false,
},
```

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens without the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Environment**
1. What version of WordPress are you using? 5.2.2
2. What version of the Gutenberg plugin are you using? (If any)

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/631 closes this issue.

**Comment by paranoia1906** [comment]
Hey @richtabor, Looks like we have merged the fix for this issue. We should be safe to close this issue as resolved.
