### ISSUE TITLE
ISNBAT edit the HTML of the Form field blocks

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#619]
**Describe the bug**
It's currently possible to edit the HTML of the child blocks within the Form block. This functionality does not work as the block is a derivative of InnerBlocks, and will cause the block to break if edited. 

**To Reproduce**

1. Add a Form block
2. Select a field child block
3. Click on the vertical ... to open the panel
4. See "Edit as HTML" listed

**Screenshots**
<img width="973" alt="Screen Shot 2019-06-28 at 12 13 57 PM" src="https://user-images.githubusercontent.com/1813435/60356478-17396d00-999f-11e9-8e1f-244f4a7fe424.png">

**Expected behavior**
The option edit the HTML of a Form field block is not present, using the following:
```
supports: {
	html: false,
},
```

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens without the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Environment**

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/631 closes this issue.
