### ISSUE TITLE
Task: Remove `icons` keyword from Share and Features blocks

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#620]
**Describe the bug**
Typing the "icons" slash command brings up the Social and Features blocks, which interferes with the Icon block, which should have priority when inserting icons.

**To Reproduce**

1. Go to the editor
2. Type in a new paragraph block `/icons`
3. See Social and Features blocks appear

**Screenshots**
<img width="602" alt="Screen Shot 2019-06-28 at 5 30 23 PM" src="https://user-images.githubusercontent.com/1813435/60372527-d9523e00-99ca-11e9-952d-fe6469b267e3.png">

**Expected behavior**
When I search for `\icon` I can easily insert an Icon block, without other blocks getting in the way. 

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens without the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**Comment by paranoia1906** [comment]
This pull closes #620
https://github.com/godaddy/coblocks/pull/630
