### ISSUE TITLE
Task: Change Share block PanelBody title to `Icon Settings`

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#621]
**Is this enhancement related to a problem? Please describe.**
Now that we've condensed the Icon and Share settings into one panel, we should properly title it `Icon Settings` (from Share Settings). 

We're also planning to implement a separate Social Profiles block, which will reuse much of this UI. Changing the title will ensure parity between the two blocks from a UI perspective.

**Describe the solution you'd like**
Change the existing PanelBody title `Share Settings` to `Icon Settings`.

**Additional context**
<img width="1097" alt="Screen Shot 2019-06-28 at 5 51 03 PM" src="https://user-images.githubusercontent.com/1813435/60373195-57174900-99cd-11e9-9391-dd2a56fd9d27.png">

**Comment by zelol** [comment]
Can I work on this?

**Comment by zelol** [comment]
"The guidelines for contributing" link on the github home page does not work.

**Comment by richtabor** [comment]
> "The guidelines for contributing" link on the github home page does not work.

Thanks for the catch. We've actually fixed that this am. [Here's the correct link](https://github.com/godaddy/coblocks/blob/master/.github/CONTRIBUTING.md) to the guidelines. And certainly, you're welcome to it!

**Comment by paranoia1906** [comment]
Pull https://github.com/godaddy/coblocks/pull/612 closes this issue. Pull also handles https://github.com/godaddy/coblocks/issues/607 and partially handles https://github.com/godaddy/coblocks/issues/504 as the block is re-factored.

**Comment by zelol** [comment]
Okay!

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/639 to close this issue.

**Comment by richtabor** [comment]
Closed by #639
