### ISSUE TITLE
Task: Update the Stacked Gallery block icon

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#623]
**Is this enhancement related to a problem? Please describe.**
The current icon is smaller than the recommended size and does not fit in well with the other gallery icons. 

**Describe the solution you'd like**
We replace the current icon with the following (using the proper SVG, Path and G components): 

```
<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="currentColor" transform="translate(2 2)"><path d="m18 0c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2h-16c-1.1 0-2-.9-2-2v-12c0-1.1.9-2 2-2zm0 14v-12h-16v12zm-5.6291504-6.02246094 3.6291504 5.02246094h-12l3.07006836-3.81713867 2.21564593 2.57547197z"/><path d="m20 20h-20c0-1.1.92707221-2 2.06016047-2h15.87967903c1.1330883 0 2.0601605.9 2.0601605 2zm0 1h-20z"/></g></svg>
```

**Additional context**
<img width="470" alt="Screen Shot 2019-06-28 at 6 39 06 PM" src="https://user-images.githubusercontent.com/1813435/60374765-0d7e2c80-99d4-11e9-8f20-3ec34e1f9c5a.png">

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/629 Pull to close this issue.
