### ISSUE TITLE
Task: Update the Carousel Gallery block icon

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#624]
**Is this enhancement related to a problem? Please describe.**
The current icon is smaller than the recommended size and does not fit in well with the other gallery icons.

**Describe the solution you'd like**
We replace the current icon with the following (using the proper SVG, Path and G components):

```
<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m18 3c1.1 0 2 .9 2 2v14c0 1.1-.9 2-2 2h-12c-1.1 0-2-.9-2-2v-14c0-1.1.9-2 2-2zm0 16v-14h-12v14zm3-14c1.1 0 2 .9 2 2v10c0 1.1-.9 2-2 2zm0 12v-10zm-18 2c-1.1 0-2-.9-2-2v-10c0-1.1.9-2 2-2zm0-12v10zm10.7857143 6 3.2142857 5h-10l2.5-3.75 1.7857143 2.5083333z" fill="currentColor"/></svg>
```

**Additional context**
<img width="478" alt="Screen Shot 2019-06-28 at 6 44 04 PM" src="https://user-images.githubusercontent.com/1813435/60374907-ba58a980-99d4-11e9-9c81-490303acceaf.png">

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/629 Pull to close this issue.
