### ISSUE TITLE
Task: Remove the custom admin footer text

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#625]
**Is this related to a problem? Please describe.**
It's not necessary to have a link to leave a review for CoBlocks at the footer of the edit.php page. 

**Describe the solution you'd like**
Remove the `CoBlocks_Admin_Footer` class (therefore removing the admin footer text). We could then also remove the `COBLOCKS_SHOP_URL` constant, as this is the only place it's used.

**Current**
<img width="473" alt="Screen Shot 2019-06-28 at 6 47 18 PM" src="https://user-images.githubusercontent.com/1813435/60374996-2f2be380-99d5-11e9-8088-5165dc4a11bf.png">

**Comment by domclone** [comment]
I can give this a go

**Comment by paranoia1906** [comment]
Created pull https://github.com/godaddy/coblocks/pull/632 to close this issue.

**Comment by richtabor** [comment]
Closed by #632
