### ISSUE TITLE
Consider `replaceInnerBlocks` instead of `insertBlock` for accordion

### ISSUE THREAD

**Issue by nicolad** [godaddy/coblocks#628]
**Is this enhancement related to a problem? Please describe.**
When I started implementing [social links](https://github.com/WordPress/gutenberg/pull/14855) for GB I took some inspiration from coblocks' accordion, more specific - the approach of adding new accordion item: https://github.com/godaddy/coblocks/blob/master/src/blocks/accordion/components/edit.js#L113

**Describe the solution you'd like**
Later I observed that in `columns` block of GB there is a different approach on adding nesting blocks items: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/edit.js#L215

Any thoughts?

**Comment by richtabor** [comment]
Thanks for pointing this out @nicolad. Is there any particular reason we should do it like core has for the Columns block?

**Comment by nicolad** [comment]
> Thanks for pointing this out @nicolad. Is there any particular reason we should do it like core has for the Columns block?

With `replaceInnerBlocks` it is easier to reason about the fact that the context is related to nested blocks. ATM I am not aware of implementation differences, but will dive deeper as I will progress on core social links block PR.

**Comment by paranoia1906** [comment]
@nicolad Thank you for the contribution of bringing ideas to the table. Do you have any followup with this? Ill go ahead and close the issue if this is a question for a later date.
