### ISSUE TITLE
ISBAT to remove to top and bottom margin for the core Group block

### ISSUE THREAD

**Issue by seb86** [godaddy/coblocks#633]
**Is this enhancement related to a problem? Please describe.**
Unable to have a clean design with space dividers because I am not able to remove the margin from the top or bottom of the group block.

**Describe the solution you'd like**
Add the option like you have done on most blocks.

**Comment by richtabor** [comment]
Good call @seb86 👍

**Comment by richtabor** [comment]
`blocksWithSpacingSupport`
