### ISSUE TITLE
Features Block - color settings inconsistent between editor and front end

### ISSUE THREAD

**Issue by jrtashjian** [godaddy/coblocks#645]
### Describe the bug
When a background color is selected on the features block it is not reflected within the editor but is on the front end. ~~When a text color is selected the SVG icon does not inherit the color on the front end like it does within the editor.~~

### To Reproduce

1. Create a new post/page and add the `coblocks/features` block to it.
2. Click on "Color Settings" panel and select any color for the background and any color for the text.
3. Save the post/page.
4. View the post/page and compare the front end with the editor.

### Screenshots

**Block Editor View**
![features-color-settings-editor](https://user-images.githubusercontent.com/375788/60622179-a682be00-9dad-11e9-9585-8ae6ba7fa9b9.png)

**Front End View**
![features-color-settings-theme](https://user-images.githubusercontent.com/375788/60622181-a8e51800-9dad-11e9-8c27-4e7db386d95a.png)

### Expected behavior
The background color should be reflected in both the editor and the front-end. ~~The selected text color should be reflected in the SVG icon color.~~

### Isolating the problem:

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

### WordPress Version

WordPress 5.2.2

### Gutenberg Version
N/A

**Comment by jrtashjian** [comment]
Edit: The SVG icon was missing from the render here. There is no issue with the icon color, just the background color.

**Comment by richtabor** [comment]
Looks to be a duplicate of #641 - unless you were getting this in all themes? I was just in TwentyNineteen.

**Comment by jrtashjian** [comment]
Sorry, I did not see that other issue. Usually the suggested issues comes up when creating a new one...

This does look to be a duplicate but I am experiencing this with other themes active. I'll close this one and continue the conversation in the #641.
