### ISSUE TITLE
System Fonts 400 Error

### ISSUE THREAD

**Issue by phpbits** [godaddy/coblocks#648]
**Describe the bug**
This issue was reported by Ben Blankley via Slack Group. Thanks!

Anyone else using CoBlocks? Mainly works well for me, but on seemingly random pages I get a 400 error because CoBlocks seems to be trying to load Arial from Google fonts. None of the paragraphs in these pages uses any non-default font, size or weight 

`<link rel='stylesheet' id='coblocks-block-fonts-css'  href='//fonts.googleapis.com/css?family=ArialHelvetica%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7C&#038;ver=1.11.0' type='text/css' media='all' />`

**Comment by richtabor** [comment]
Good find @phpbits - wanna put together a PR for this? 🙏

**Comment by richtabor** [comment]
We need to ignore [the default system fonts](https://github.com/godaddy/coblocks/blob/master/src/components/font-family/index.js#L15-L21) when retrieving Google fonts within the editor, as those don't exist on GF.

They should remain as selectable font options, just not trigger a call to `https://fonts.googleapis.com/`.
