### ISSUE TITLE
Task: Improve social icons

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#649]
**Is this enhancement related to a problem? Please describe.**
The variation in size/viewBox of the social icons causes the icons to not look as nice and congruent as they could.

**Describe the solution you'd like**
Replace the current `dist/images/social/` SVG icons with the contents within [this zip](https://github.com/godaddy/coblocks/files/3363775/new-social-icons.zip).

<img width="568" alt="after" src="https://user-images.githubusercontent.com/1813435/60741435-5f283900-9f37-11e9-9502-42f587cf520e.png">

**Comment by paranoia1906** [comment]
https://github.com/godaddy/coblocks/pull/657 closes this issue.
