### ISSUE TITLE
Need ability to disable ul/ol "Styles" options

### ISSUE THREAD

**Issue by onetrev** [godaddy/coblocks#656]
The included **Styles** options for _list blocks_ while it could be handy in some cases, it causes headaches as well because the styling is very much reliant on theme you are using. The CoBlocks list styles rely on your `line-height` + `font-size` combination to position the bullets, so while it looks fine in say Twenty Nineteen theme, in my custom theme it ends up looking like this out of the box:

![Annotation 2019-07-08 151423](https://user-images.githubusercontent.com/597601/60784958-7dd73b80-a194-11e9-8231-305572b15717.jpg)

As such it would be really handy to have an option to _disable_ features such as these, so developers are not left having to style all these new classes in custom build sites when they want to use other features of CoBlocks. Thanks!!

Also note, for some reason no matter what theme I use, even Twenty Nineteen, I just get a big solid circle, there is no checkmark in the SVG.

**Comment by richtabor** [comment]
Hey @onetrev, I'm not exactly following (on part 1). You're wanting a way to completely disable the styles selector for the List block that CoBlocks adds? If so, I'm not actually sure if that's possible right now in Gutenberg. Thoughts @jrtashjian?

<img width="339" alt="Screen Shot 2019-07-08 at 10 13 34 PM" src="https://user-images.githubusercontent.com/1813435/60854284-a7608900-a1cd-11e9-858c-b8369f1559d4.png">

**Comment by richtabor** [comment]
> Also note, for some reason no matter what theme I use, even Twenty Nineteen, I just get a big solid circle, there is no checkmark in the SVG.

I've opened another issue with this particular bit in it so we don't loose it. Thanks for the report. 👍

**Comment by onetrev** [comment]
Hey @richtabor you got it exactly right on part one. My apologies though, I really should have included a screenshot to make easier. (A picture is still worth 1000 words even these days).

So ya not a major issue if this can't be done. I may have overreacted. I love and hate Gutenberg at the same time. Really in the end for those building bespoke / custom builds Gutenberg and plugins for it such will just take a bit of extra time at the start as we build up a nice base collection of classes to style the output.

Perhaps instead of allowing the Styles tab to be hidden, maybe there could be documentation (for developers) outlining any items such as these and the class names we can hook into to customize the output?

And sorry, I should have opened another issue for the other item, my bad, thanks for creating that!

**Comment by richtabor** [comment]
> Perhaps instead of allowing the Styles tab to be hidden, maybe there could be documentation (for developers) outlining any items such as these and the class names we can hook into to customize the output?

Good idea. For now, you could use the `.is-style-checkbox` class to target the checkbox style. Most of the styles for most blocks will use that class structure for styling. 

I'll close this initial issue (as I split out the other) but we'll look into better developer docs for sure in the future. 👌
