### ISSUE TITLE
ISBAT apply a custom font size to the Highlight block without breaking it

### ISSUE THREAD

**Issue by jrtashjian** [godaddy/coblocks#667]
### Describe the bug
When the font size setting in the sidebar is set to "small", "large", or "huge" the block breaks upon reloading the block editor. The `fontSize` attributes looks to have been saved when viewing the block output in the "Code Editor" view (before reloading). However when reloading the block-editor the attribute does not seem to exist. This is causing block validation to fail. If the font size selected is "normal", there are no issues.

### To Reproduce

1. Add the Highlight block to a post and add some text.
2. Save the post and reload the page.
3. Note that the block loads without issue.
4. Select a new font size under the "Text Settings" panel in the sidebar.
5. Save the post and reload the page.
6. You should see the block validation error shown in place of the block.

### Screenshots

**Block working with default settings**

![Screenshot from 2019-07-15 17-07-38](https://user-images.githubusercontent.com/375788/61249672-d625b480-a723-11e9-80e9-89625bb29055.png)

**Code Editor view with "large" font size selected (before reloading block editor)**
![Screenshot from 2019-07-15 17-14-45](https://user-images.githubusercontent.com/375788/61249810-256be500-a724-11e9-85c0-fde916792f5a.png)

**Broken block with "large" font size selected (after reloading the block editor)**
![Screenshot from 2019-07-15 17-15-49](https://user-images.githubusercontent.com/375788/61250029-ad51ef00-a724-11e9-95cf-13bf517f7f32.png)

### Expected behavior
The block should pass validation and show the block edit with the correct attributes present.

### Isolating the problem:

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

### WordPress Version
What version of WordPress are you using?
5.2.2

### Gutenberg Version
What version of the Gutenberg plugin are you using? (If any)
N/A

**Comment by richtabor** [comment]
May be that `withFontSizes( 'fontSize' ),` should be added to the inspector.js - but I'm not 100% sure.
