### ISSUE TITLE
Remove list indention controls on the Pricing Table block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#676]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Reported via [Issue 16650](https://github.com/WordPress/gutenberg/issues/16650) on the Gutenberg repository. 

**To Reproduce**

1. Add a Pricing Table block
2. Click on the "Add features" placeholder text
3. See the list indention controls in the block toolbar

**Screenshots**
<img width="1101" alt="Screen Shot 2019-07-17 at 8 22 55 PM" src="https://user-images.githubusercontent.com/1813435/61420487-ba134600-a8d0-11e9-8194-8e7dec4efcbf.png">

**Expected behavior**
No controls are rendered, as they are not necessary.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**Comment by richtabor** [comment]
Looks like this may have been resolved by core (https://github.com/WordPress/gutenberg/pull/16962). I have not double-checked, but if so we're good to close this one. 

@paranoia1906 Mind running the latest from The Gutenberg repo and confirming?

**Comment by paranoia1906** [comment]
As of today, the latest changes with Gutenberg resolve this issue. Closing this issue now as fixes are coming down the pipe.

![gutenbergLatestChangesIndentList](https://user-images.githubusercontent.com/30462574/63541774-aeb8c900-c4d3-11e9-8b4f-598a41b12457.gif)
