### ISSUE TITLE
Hero Block with background image covering other block's settings

### ISSUE THREAD

**Issue by retnonindya** [godaddy/coblocks#685]
**Describe the bug**
When creating a new block after Hero Block, the settings/options on the next block is covered by Hero Block if the Hero Block is having background image.

**To Reproduce**
Create Hero Block and add Image Background for the Hero Block.

![image](https://cldup.com/9bF817z1Vx.png)
*Direct link: https://cldup.com/9bF817z1Vx.png*

Create new block under Hero Block.

Click on the Block and try to edit or change the block. It's being covered by Hero Block above it.

![new block](https://cldup.com/db1FlowC0E.png)
*Direct link: https://cldup.com/db1FlowC0E.png*

The block's settings won't be obstructed/covered when the Hero Block is not using any image background.

![not covered](https://cldup.com/Mutw9g7CKb.png)
*Direct link: https://cldup.com/Mutw9g7CKb.png*

**Expected behavior**
I can still see the block's settings when the block is clicked.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated. This is a Simple site (Premium plan)
-   [x] This bug happens with a default WordPress theme active. I use Independent Publisher 2 theme
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
Since the site is Simple, it would be the latest version (5.1.1, I presume.)

**Comment by richtabor** [comment]
I've confirmed the issue. I believe adding a `z-index: 0` to `.wp-block[data-type="coblocks/hero"]` should resolve this.

**Comment by retnonindya** [comment]
5 days late of me, but thank you so much, @richtabor! Thank you!
