### ISSUE TITLE
ISBAT align Stacked block images left or right

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#695]
**Is your feature request related to a problem? Please describe.**
With the Image block I am able to align the image to the left or right of the block and add text which will wrap around the image.  Using the Stacked block I have only Wide or Full-screen layout options and have no ability to wrap text.

**Describe the solution you'd like**
Can we consider adding the layout options to the Stacked Block for left/right align similar to Image block.

**Describe alternatives you've considered**
An alternative to this approach is using several Image blocks layered in rows. This allows the alignment and wrapping.

**Additional context**
![image](https://user-images.githubusercontent.com/30462574/61909545-4c29d880-aee7-11e9-9863-4304e029ea31.png)

**Comment by paranoia1906** [comment]
Originally reported on WordPress.org

https://wordpress.org/support/topic/image-stack-floated-right/

**Comment by richtabor** [comment]
This would be done by adding left, right and center to ‘align’ supports. And we’d need to make sure that if a user selects left or right aligned, the ‘Fullwidth’ toggle is turned off, as you can’t have left aligned and fullwidth.

**Comment by paranoia1906** [comment]
Looks like the only having a single align set at a time is now supported by core. 

![stackedAlignmentToggle](https://user-images.githubusercontent.com/30462574/63694648-c17d1780-c7cb-11e9-9cc9-1fa261b589c4.gif)

https://github.com/godaddy/coblocks/pull/776
