### ISSUE TITLE
DimensionsControl breaks with Gutenberg 6.3.0

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#730]
**Describe the bug**
The display of the DimensionsControl component is breaking when the Gutenberg 6.2.0 plugin is active. This applies to all blocks that use the DimensionsControl component.
`Row Block`
`Hero Block`
`Media Card Block`

**To Reproduce**

1. 'Add any effected component'
2. 'Access block settings inspector`

**Screenshots**
### Gutenberg Deactivated
![image](https://user-images.githubusercontent.com/30462574/62835623-7bdb1f00-bc0f-11e9-8102-3869db1ee44d.png)

![image](https://user-images.githubusercontent.com/30462574/62835628-839ac380-bc0f-11e9-820a-41fb53fe1732.png)

![image](https://user-images.githubusercontent.com/30462574/62835634-944b3980-bc0f-11e9-9c8c-a0824a5462a2.png)

### Gutenberg Activated
![image](https://user-images.githubusercontent.com/30462574/62835591-2bfc5800-bc0f-11e9-90cf-2b625fbbd1be.png)

![image](https://user-images.githubusercontent.com/30462574/62835595-39b1dd80-bc0f-11e9-8024-cf5e8a08bfbb.png)

![image](https://user-images.githubusercontent.com/30462574/62835605-4b938080-bc0f-11e9-93e7-6c9cedd863e9.png)

**Expected behavior**

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.2
**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
6.2.0

**Comment by paranoia1906** [comment]
Looks to be rooted in a style change in `font-size-picker` to use select.

`Change font-size-picker markup to use select`  

https://github.com/WordPress/gutenberg/commit/49124712753d8fbb424afc8fc184f013a12d67f1#diff-f8a6163a171cae350441a1a4bfa7c155

**Comment by richtabor** [comment]
Icon block also has the same issue: 
<img width="324" alt="Screen Shot 2019-08-15 at 10 34 35 AM" src="https://user-images.githubusercontent.com/1813435/63102183-9e8b7180-bf48-11e9-81a8-61b1dd294969.png">
