### ISSUE TITLE
Move CoBlocks top-level admin menu item

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#739]
**Is this enhancement related to a problem? Please describe.**
The `CoBlocks` top-level menu item does not need to be top-level, as the plugin does not require any sub items. It's great as the page contains introduction text and a couple videos (which we can extend in the future to more even), but it should not be top-level.

**Describe the solution you'd like**
Move the `CoBlocks` top-menu item to an existing sub menu, perhaps `Tools`?

**Describe alternatives you've considered**
We have a filter in place (which can remain) but this isn't a great option for less-developer-oriented folks. 

**Additional context**
<img width="1184" alt="Screen Shot 2019-08-14 at 11 06 02 AM" src="https://user-images.githubusercontent.com/1813435/63032282-830a6300-be83-11e9-8696-a6b07a3d1420.png">

**Comment by richtabor** [comment]
@fjarrett Thoughts on where it should be moved?

**Comment by paranoia1906** [comment]
Thinking about this from the users perspective, one might expect to be allowed to access settings if they were to go into the settings menu. The CoBlocks menu page, at this time, has no settings to interact with. As you state @richtabor, the page has information and videos about the plugin (read tool). 

For this reason I suggest that CoBlocks menu be moved under Tools.
