### ISSUE TITLE
Hero inner blocks are missing when added from inserter

### ISSUE THREAD

**Issue by mmtr** [godaddy/coblocks#750]
**Describe the bug**
The inner blocks of the Hero blocks are missing when the block is added using the block inserter (the dialog that shows up after clicking on the '+' icon). However, the inner blocks appear as expected when adding the block typing the `/` shorcut.

This issue is not reproducible when the Gutenberg plugin is not activated.

**To Reproduce**
1. Activate the latest version of the Gutenberg plugin.
1. Click on the "+" icon to open the block inserted.
1. Select the Hero block.
1. Notice how the inner blocks are missing.
1. Repeat the above steps, but this time insert the block by typing `/hero` on the post content.
1. Note how the inner blocks are correctly rendered now.

**Screenshots**
![Aug-20-2019 11-54-46](https://user-images.githubusercontent.com/1233880/63314219-eb54bb00-c341-11e9-9236-d9254c1cb4d2.gif)

**Expected behavior**
Inner blocks should appear after inserting a hero block.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.0

**Gutenberg Version**
6.3.0

**Comment by paranoia1906** [comment]
- Nothing is logged to console when adding a Hero block this way.
- Confirmed issue only occurs when 6.3 Gutenberg is enabled.
