### ISSUE TITLE
Missing description for Services Block

### ISSUE THREAD

**Issue by jrtashjian** [godaddy/coblocks#752]
### Describe the solution you'd like
We just need to add a short description to the `coblocks/services` and `coblock/service` block.

### Additional context
![Screenshot from 2019-08-20 11-31-20](https://user-images.githubusercontent.com/375788/63361709-995e6600-c33e-11e9-97c0-f0eb8e015416.png)

**Comment by richtabor** [comment]
`Add up to four columns of services to display.`
