### ISSUE TITLE
Share/Social Profile style previews are rendered incorrectly

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#760]
**Describe the bug**
Social Profiles and Share block SVGs under Styles sidebar option do not render correctly with Gutenberg 6.3 active.

**To Reproduce**

1. Add Social Profiles or Share blocks.
2. View block sidebar and expand Styles option.
3. See issue.

**Screenshots**
### Without Gutenberg 6.3
![image](https://user-images.githubusercontent.com/30462574/63431945-ea209e00-c3d4-11e9-8c5f-439b780beb23.png)

### Gutenberg 6.3 active
![image](https://user-images.githubusercontent.com/30462574/63432005-0a505d00-c3d5-11e9-8f0f-618e9891aa66.png)

**Expected behavior**
SVGs should be a reasonable size regardless of status of Gutenberg Plugin.

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.2

**Gutenberg Version**
6.3.0

**Comment by richtabor** [comment]
Does this also apply to the Services block?

**Comment by richtabor** [comment]
May be related to #753.

**Comment by richtabor** [comment]
This looks like a purposeful addition in core.. 
<img width="358" alt="Screen Shot 2019-08-23 at 11 25 48 AM" src="https://user-images.githubusercontent.com/1813435/63604014-c60dba00-c598-11e9-865a-5baa52bc24fe.png">
