### ISSUE TITLE
ISBAT remove the background color from the Hero block

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#766]
**Describe the bug**
It's not possible to completely remove the background color from the Hero block. Doing so will result in a "This block contains unexpected or invalid content" notice.

**Screenshots**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/63455609-16f7a400-c41b-11e9-8702-24bec3de79cb.gif)

**Expected behavior**
The background color is removed and the block doesn't break when doing so.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.2.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
Does it with both.

**Comment by paranoia1906** [comment]
This is a duplicate issue of https://github.com/godaddy/coblocks/issues/729
