### ISSUE TITLE
Click to Tweet replaces bold/italic text with [object Object]

### ISSUE THREAD

**Issue by jacoswan** [godaddy/coblocks#772]
**Describe the bug**
It is possible to paste formatted text into the Click to Tweet block. Then, in the resulting tweet the words that are bold and/or italic is replaced with the words `[object Object]`

**To Reproduce**

1. Add some paragraph text to a post or page, bold/italicize some of the words
2. Copy that text
3. Add a Click to Tweet CoBlock, and paste your copied text.
4. Publish and view the page on the front-end
5. Click the `Tweet` button below the text
6. Once on twitter.com, notice the display of [object Object] instead of bold/italic text

**Screenshots**

In the editor it looks like this:
![In Editor](https://cld.wthms.co/HNM7Ar+)

On the front-end it looks like this:
![Front-end](https://cld.wthms.co/CmaPkW+)

After clicking the Tweet button it looks like this:
![On twitter.com](https://cld.wthms.co/Kw8epd+)

**Expected behavior**
For the tweet to be displayed properly, possibly stripping tags before sending to twitter. 

Or, stripping it in Click to Tweet CoBlock itself, because when the editor is exited and re-entered, it does highlight a conflict: 

![Conflict 1](https://cld.wthms.co/QzDw09+)
![Conflict 2](https://cld.wthms.co/ya46gT+)

When clicking resolve, it converts it to a Quote Block in the editor (although it still functions as a Click to Tween block on the front end after, and leads to the same error): 

![Quote Block](https://cld.wthms.co/CgTLJ4+)
![Quote / Tweet](https://cld.wthms.co/OmW4qE+)

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.2

**Gutenberg Version**
6.2.0

**Comment by paranoia1906** [comment]
- Confirmed that the issue happens **with** and **without** Gutenberg active.
- Issue was present in CoBlocks 1.11.1.
