### ISSUE TITLE
Row block has both Layout and Styles panels

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#816]
**Describe the bug**
The Row block shows both `Layout` and `Styles` panels within the Settings Sidebar, whereas we only need the Styles panel. They both perform exactly the same.

**To Reproduce**

1. Add a Row block
2. Select any number of columns and get to the stage where you may add blocks
3. Open the Settings Sidebar

**Screenshots**
<img width="1344" alt="Screen Shot 2019-09-01 at 11 27 35 AM" src="https://user-images.githubusercontent.com/1813435/64078694-b9c9e100-ccab-11e9-971c-5f9837080394.png">

**Expected behavior**
Only the "Styles" panel exists, not the "Layout" panel. 

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**Comment by paranoia1906** [comment]
Question @richtabor, the label for the styles is currently referencing layouts.

![image](https://user-images.githubusercontent.com/30462574/64080266-e7f8f200-cca6-11e9-8ed3-d0d3f7f4490f.png)

Should we update the label to say `Change Style` to match the wording from the block inspector?

**Comment by richtabor** [comment]
> Question @richtabor, the label for the styles is currently referencing layouts.

I think it's ok to keep layout in there for now. Eventually I'd like to update that control the same way I've done the Pricing Tables count in #811 (screenshot below): 

![](https://user-images.githubusercontent.com/1813435/64070636-091ffb00-cc33-11e9-92bc-c5a4a1f3bee4.gif)
