### ISSUE TITLE
Page editor white screen when using Hero block and upgrading 1.12.0 > 1.12.1

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#822]
**Describe the bug**
A block validation failure occurs for the hero block which results in total editor crash.

```html
Block validation: Block validation failed for `coblocks/hero`...

Content generated by `save` function:

<div class="wp-block-coblocks-hero alignfull coblocks-hero-8354612371"><div class="wp-block-coblocks-hero__inner has-background hero-center-left-align has-padding has-huge-padding" style="background-color:#f3f3f3;min-height:500px"><div class="wp-block-coblocks-hero__content-wrapper"><div class="wp-block-coblocks-hero__content" style="max-width:560px"></div></div></div></div>

Content retrieved from post body:

<div class="wp-block-coblocks-hero alignfull coblocks-hero-8354612371"><div class="wp-block-coblocks-hero__inner has-background hero-center-left-align has-padding has-huge-padding" style="background-color:#f3f3f3;min-height:500px"><div class="wp-block-coblocks-hero__box" style="max-width:560px"></div></div></div>
```
**The editor crashes as well**

```javascript
TypeError: r is undefined    blocks.build.js:1:613988
    save http://ledesma.tech/gutenberg/wp-content/plugins/coblocks/dist/blocks.build.js?ver=1567514846:1
```

```javascript
The above error occurred in the <EditorProvider>    component: react-dom.js:17206:13
    in EditorProvider (created by ComponentWithDispatch)
    in ComponentWithDispatch (created by Context.Consumer)
    in WithDispatch(EditorProvider) (created by ComponentWithSelect)
    in ComponentWithSelect (created by Context.Consumer)
    in WithSelect(WithDispatch(EditorProvider)) (created by Editor)
    in StrictMode (created by Editor)
    in Editor (created by ComponentWithSelect)
    in ComponentWithSelect (created by Context.Consumer)
    in WithSelect(Editor)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**To Reproduce**

1. Install 1.12.0
2. Edit page and add Hero block. Publish.
3. Go to plugins page and update CoBlocks to 1.12.1.
4. Edit same page with Hero block to find white page. Open element inspector to see detailed error messages. 

**Expected behavior**
Editor should not crash with a block validation failure. 

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A

Reported on WordPress.org
https://wordpress.org/support/topic/updated-coblocks-is-breaking-the-page-editor-for-pages-using-the-hero-block/

**Comment by richtabor** [comment]
It looks like that for some reason the deprecation didn't catch this from `wp-block-coblocks-hero__box` to `wp-block-coblocks-hero__content-wrapper` - although it's in place. 

It's interesting that the editor white-screens and doesn't just through a validation error. Makes me wonder if this is something else behind-the-scenes and not deprecation?

**Comment by richtabor** [comment]
It's also interesting that their innerBlocks content is not saved..

**Comment by richtabor** [comment]
@paranoia1906 Let me know if you can replicate this - I'm having trouble doing so.

**Comment by jrtashjian** [comment]
> It's also interesting that their innerBlocks content is not saved.

IIRC the InnerBlocks content is saved but block validation only cares about the current block its validating. So it will look like the InnerBlocks are missing but they are removed for validation and prevents us having to provide deprecations for the InnerBlocks blocks.

**Comment by jrtashjian** [comment]
I believe #809 might resolve the issue here but I'll need to test this.

**Comment by paranoia1906** [comment]
@richtabor
I have been able to replicate the error using these steps.

> - Install 1.12.0
>  - Edit page and add Hero block. Publish.
>   - Go to plugins page and update CoBlocks to 1.12.1.
>   - Edit same page with Hero block to find white page. Open element inspector to see detailed error messages.

**Comment by jrtashjian** [comment]
@richtabor what's the reason for this conditional? I'm not seeing `this.props.insertBlocksAfter` being used for anything within the conditional. Was this for an older version of the Gutenberg plugin to enable new features that weren't added to core yet?

**Comment by richtabor** [comment]
> @richtabor what's the reason for this conditional? I'm not seeing `this.props.insertBlocksAfter` being used for anything within the conditional. Was this for an older version of the Gutenberg plugin to enable new features that weren't added to core yet?

It may have been just for that. Possibly `innerBlocks` related with the inserter?

**Comment by DustinWStout** [comment]
I was just about to submit a ticket about this. Happening on my sites too... same process, same results.

**Comment by jrtashjian** [comment]
@DustinWStout We're planning to push a new release out tomorrow with this fix.
