### ISSUE TITLE
Masonry: Incorrect height on site but correct in WP

### ISSUE THREAD

**Issue by MartinSoderholm** [godaddy/coblocks#837]
## Prerequisites

-   [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
-   [x] The issue still exists against the latest `master` branch of CoBlocks on Github (this is **not** the same version as on WordPress.org!)
-   [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Add the Masonry gallery block in a page.
2. Add images and save.

Am currently working in a local dev env so unfortunately I can't link to a page with the error.

## Expected/actual behavior

<img width="1628" alt="Screenshot 2019-09-07 at 10 10 03" src="https://user-images.githubusercontent.com/3729799/64472108-92ff2500-d159-11e9-8552-54e57286274d.png">

## Isolating the problem

-   [x] This bug happens with only CoBlocks plugin active
-   [ ] This bug happens with a default WordPress theme active **(Not in Twenty Nineteen)**
-   [x] I can reproduce this bug consistently using the steps above

I have narrowed down the issue to these lines of CSS:
```scss
.wp-block-coblocks-gallery-masonry {
    img {
        max-width: 100%;
        height: auto;
    }
}
```
If I simply add these img styles the problem is fixed. These lines are also present in the Twenty Nineteen theme.

## WordPress Environment

The issue is present for me in Chrome (76.0.3809.132) and Safari (12.1.2), and the issue is present in a bare bones theme with no theme css. The issue is NOT present in a standard WP theme (Twenty Nineteen).

```
Wordpress 5.2.3
Coblocks 1.13.0
```

**Comment by richtabor** [comment]
Hey @MartinSoderholm, thanks for the report. Do you have a live URL we could take a look at to check it out? Most likely there’s a JavaScript conflict, or lazy-loading perhaps, that is causing an issue.

**Comment by MartinSoderholm** [comment]
There's no live URL unfortunately. The javascript seems to be working fine (images reorder and layout on window resize), and the issue remains even if I remove all theme js & css. I searched the css in your plugin dir and could not find the required img styles. Have you tested your plugin with a bare bones theme?

**Comment by Robertght** [comment]
Howdy! I can confirm the issue as we tested on a WordPress.com site with the Lazy images form Jetpack  turned on.

**Comment by paranoia1906** [comment]
**Example Gallery in twentynineteen**
![image](https://user-images.githubusercontent.com/30462574/65980900-e731b800-e42c-11e9-87f4-772599ba18c3.png)
 
**Example Gallery in barebones theme**
![image](https://user-images.githubusercontent.com/30462574/65980969-06c8e080-e42d-11e9-996b-23e14a6baae4.png)

**Example Gallery in barebones theme after adding standard CSS for class `.entry-content`**
![image](https://user-images.githubusercontent.com/30462574/65982597-8dcb8800-e430-11e9-843e-c2c95866e92e.png)

Issue seems to be relating to lack of page/post specific css. 
https://github.com/WordPress/twentynineteen/blob/b604f127c2cae10bd48bbbec0fbbbff2cd31f957/style.css#L2648
I was able to get a similar feel to the Gallery in Twentynineteen by adding the following to my barebones theme css.

```css
body {
   max-width: 80%;
   margin: 0 10%;
   padding: 0 60px;
}
```

Should the block be expected to handle cases where styles are missing? Should the theme be expected to handle cases where block style may be effected? What are your thoughts @richtabor @jrtashjian.

**Comment by jrtashjian** [comment]
We shouldn't be concerned with theme styles or the markup provided by the theme. All styles we provide should be limited to our own block class and child elements. Our block should display and function how we expect it to regardless of theme and the theme has the ability to override these styles.

**Comment by richtabor** [comment]
> There's no live URL unfortunately. The javascript seems to be working fine (images reorder and layout on window resize), and the issue remains even if I remove all theme js & css. I searched the css in your plugin dir and could not find the required img styles. Have you tested your plugin with a bare bones theme?

Yea, and I'm having trouble replicating this honestly. I do see an issue with JetPack's lazy loading module, where the masonry is waiting for a resize event - but without any styling, and any JS, the masonry image are not display as in your screenshot there. 

I'm not seeing any side-effects of adding that proposed styling though I'm intrigued about the original cause of what's happening. :/
