### ISSUE TITLE
ISBAT set text alignments without the use of inline styling

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#850]
**Is this enhancement related to a problem? Please describe.**
Inline styles should be a last resort when applying styling to blocks. When WordPress 5.3 is released, Gutenberg will be updated to use utility classes, such as `.has-text-align-center` to apply alignments, so we should follow suite. 

Here are blocks that we should tweak and provide proper deprecation support for: 

- [x] Alert
- [x] ~~Author (is not necessary, as the #808 PR removes this capability anyhow)~~
- [x] Click to Tweet
- [x] Pricing Table
- [x] Row
- [x] Social Profiles (#931)
- [x] Share 
- [x] Icon

**Describe the solution you'd like**
Each inline text align style is replaced with `.has-text-align-{value}` classes.

**Comment by jrtashjian** [comment]
Just a future reminder that we should create multiple PRs for each block that's changed.

**Comment by jrtashjian** [comment]
All tasks completed.
