### ISSUE TITLE
ISBAT add reusable blocks to Accordion block

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#888]
**Is this enhancement related to a problem? Please describe.**
At this time there are a limited set of blocks allowed within an Accordion block. This is a proposal to open up options to allow reusable blocks within an Accordion block.

**Describe the solution you'd like**
Ability to add reusable blocks to Accordion block.

**Describe alternatives you've considered**
We may also want to consider allowing others outside of reusable Row, Alert, Image, Share, Highlight, Button, Heading, List, or Columns blocks within accordion and perhaps allow most if not all blocks. 

**Additional context**
**Here is the interface for the row block.**
![image](https://user-images.githubusercontent.com/30462574/65161912-446d4880-d9ed-11e9-91c6-e6962d02e92d.png)

**Whereas the Accordion block only allows a few.**
![image](https://user-images.githubusercontent.com/30462574/65164389-a3cd5780-d9f1-11e9-868a-33acc08925cf.png)

**Inspired by WordPress.org support request**
https://wordpress.org/support/topic/accordion-doesnt-support-reuseable-blocks/

**Comment by jrtashjian** [comment]
Absolutely agree. We shouldn't limit the blocks that can be used unless it absolutely makes sense to do so. For example, the Food and Drinks block and the Author block.
