### ISSUE TITLE
ISBAT apply custom margin and padding to Row block

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#893]
**Describe the bug**
When using dimensions controls for the Row block you are able to go into 'Advanced' options and set values for horizontal and vertical padding and margins. At this time CoBlocks is not saving content including custom margins applied inline as is shown within the editor. This will likely require a deprecation of the current save function and a change in the save function properly apply inline styles.

**Applied in editor**
https://github.com/godaddy/coblocks/blob/ee6ba42ba793528c9b0b65c50c3ce445968144b0/src/blocks/row/edit.js#L303

**Not applied in save function**
https://github.com/godaddy/coblocks/blob/ee6ba42ba793528c9b0b65c50c3ce445968144b0/src/blocks/row/save.js#L64

**To Reproduce**

1. Add a row block and insert blocks into columns. 
2. Select the row block and apply custom values for margins or padding.
3. Notice that changes are visible within the editor.
4. Publish changes and view page to see that custom values are not saved to front-end.

**Screenshots**
**Display within the editor**
![image](https://user-images.githubusercontent.com/30462574/65180154-14d03780-da11-11e9-86f5-6c7a718f326e.png)

**Front of site**
![image](https://user-images.githubusercontent.com/30462574/65180114-03872b00-da11-11e9-9ce7-56c462582db8.png)

**Expected behavior**
Expect custom CSS values to be applied both in editor and on front-of-site.

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
6.5 (optional)

**Inspired by WordPress.org report**
https://wordpress.org/support/topic/margins-on-columns/

**Comment by richtabor** [comment]
Note that this does not occur when the Gutenberg plugin is deactivated.

**Comment by richtabor** [comment]
And the styles are not applied to the save function, as they are generated [here](https://github.com/godaddy/coblocks/blob/master/includes/class-coblocks-generated-styles.php#L59) to target the first div within the specific block.

**Comment by richtabor** [comment]
This is relative/addresses the same issue? https://github.com/godaddy/coblocks/pull/543

**Comment by paranoia1906** [comment]
#543 is merged and this issue is closed.

**Comment by ticktickatick** [comment]
Custom padding values on rows still do not work in Preview on a Published post. You have to completely save the Post for the custom padding to show up in Preview on an already Published post.

Custom padding values on rows DO work in Preview on a Draft post.

**Comment by richtabor** [comment]
> Custom padding values on rows still do not work in post Preview on a _Published_ post but changes not yet published. You have to completely save/publish the Post changes for the custom padding to show up in Preview on an already Published post.
> 
> Custom padding values on rows DO work in Preview on a _Draft_ post.

Do you mind opening a new issue referencing the post preview here? That’s a separate issue imo. Thanks!
