### ISSUE TITLE
ISNBAT access Row layout toolbar before selecting a layout

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#898]
**Describe the bug**
Using the Row block we must first select the number of columns and then the layout of said columns. The bug is that the layout styles toolbar button is made available before a layout has been chosen.

**To Reproduce**

1. Add row block and choose 1-4 columns.
2. Notice the toolbar item with no icon.

**Screenshots**
![missing-layout-icon](https://user-images.githubusercontent.com/30462574/65260649-8d8bce00-dabb-11e9-8217-a891a8d59d8a.gif)

**Expected behavior**
Expect that the layout toolbar controls are not available until an initial layout has been selected. 

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A

**Comment by EvanHerman** [comment]
Good catch. I'll squash this one today 💪
