### ISSUE TITLE
ISBAT add a popular food item to my site's food menu

### ISSUE THREAD

**Issue by paranoia1906** [godaddy/coblocks#902]
**Is this enhancement related to a problem? Please describe.**
Many restaurants have popular or favorite dishes which may sell more then others. Perhaps its a dish that makes the restaurant famous. We should allow site owners to mark select food items as popular with a block attribute. 

**Describe the solution you'd like**
Add checkbox to block sidebar to allow a mechanism indicating a popular dish.

**Describe alternatives you've considered**
At this time one would need to style a Food & Drinks block separately to get a special look for a single food item or a set of food items. 

**Additional context**
Here is a quick mock-up which shows where interface controls are expected.
![image](https://user-images.githubusercontent.com/30462574/65264055-a6e44880-dac2-11e9-9050-911e401de7da.png)

**SVG Icon to use when marking food items poular**
[popular.zip](https://github.com/godaddy/coblocks/files/3677698/popular.zip)

**Comment by richtabor** [comment]
SVG to use for the popular icon: 

```<SVG xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"><Path d="m17.772 6.972c-.0709465-.21754688-.2594538-.3757999-.486-.408l-5.352-.78-2.4-4.848c-.10025187-.2069942-.31000645-.33846606-.54-.33846606s-.43974813.13147186-.54.33846606l-2.4 4.848-5.352.78c-.22773507.03099757-.41775154.18936436-.48928114.40778512-.07152961.21842076-.01200158.45850973.15328114.61821488l3.876 3.774-.9 5.334c-.03420413.2211269.05747884.4429149.23783705.5753457.18035822.1324309.41942265.1534994.62016295.0546543l4.8-2.514 4.8 2.514c.2016738.1054991.4456774.0878057.6300214-.0456848.1843439-.1334904.2772862-.3597923.2399786-.5843152l-.912-5.334 3.876-3.774c.1598073-.16298049.2132968-.40252052.138-.618z" fillRule="evenodd" /></SVG>```
