### ISSUE TITLE
Composer and WPackagist compatibility

### ISSUE THREAD

**Issue by brenoalvs** [godaddy/coblocks#905]
Hey guys, can you create tags into your WordPress.org SVN repository so WPackagist will show up all available versions?

I think that makes sense create a composer.json file within the plugin too.

Currently it's only possible install the latest version using Composer.
https://wpackagist.org/search?q=coblocks&type=plugin

My team and I started using Coblocks 1.13.x via Composer in the last week and this version is not available anymore in WPackagist so it may break any Composer-based workflow.

Let me know if there's anything else I can help you.

**Comment by fjarrett** [comment]
Not having tags also prevents being able to pin to certain versions via WP-CLI:

```
wp plugin install coblocks --version=1.13.0
```

**Comment by jrtashjian** [comment]
I backfilled the tagged releases until version 1.12.0. Using WPackagist and WP-CLI should be working now:

```
wp plugin install coblocks --version=1.13.0 --activate
Installing Page Builder Gutenberg Blocks – CoBlocks (1.13.0)
Downloading installation package from https://downloads.wordpress.org/plugin/coblocks.1.13.0.zip...
The authenticity of coblocks.1.13.0.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'coblocks'...
Plugin 'coblocks' activated.
Success: Installed 1 of 1 plugins.
```

We will need to update our CI deploy script to properly tag each version in SVN after each deploy.

**Comment by EvanHerman** [comment]
Updates to the deploy script to create the tag on SVG done in #949
