### ISSUE TITLE
ISBAT tweak the height of the Map block via the Settings Sidebar

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#950]
**Describe the bug**
Our current "Height in pixels" `RangeControl` for the Map block is not following Gutenberg's UX pattern for adjusting the height of blocks. It should be updated to resemble the Shape Divider's `BaseControl`.

**To Reproduce**

1. Add the Map block
2. Open the Settings Sidebar
3. Attempt to change the Height in pixels control

**Screenshots**
Current Spacer block (what the Map block control should be): 
<img width="353" alt="Screen Shot 2019-10-07 at 12 09 32 PM" src="https://user-images.githubusercontent.com/1813435/66328859-73475200-e8fb-11e9-82d3-959f0a770f14.png">

**Expected behavior**
A new `BaseControl` height control replaces the existing RangeControl.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any) 6.4

**Comment by richtabor** [comment]
> @richtabor can't resize using the sidebar controls anymore. Using latest Gutenberg (v6.7.0) with the latest CoBlocks (v1.15.0).

Hey @hacknug, this PR fixes that bug, which also bringing the UX to follow Gutenberg's UX pattern. 👍

**Comment by hacknug** [comment]
Perfect. Couldn't test this locally so I thought I'd bring it up in case this PR or a previous one introduced the bug. Thanks!
