### ISSUE TITLE
ISBAT apply formats to my text (bold, italic, etc)

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#980]
**Describe the bug**
There's an issue where CoBlocks is overriding the formatting controls provided by core. This is happening with and without the Gutenberg plugin active. 

**To Reproduce**
1. Add a Paragraph block
2. Type in text
3. Look at the block toolbar

**Screenshots**
With CoBlocks activated: 
<img width="1118" alt="Screen Shot 2019-10-11 at 11 07 29 AM" src="https://user-images.githubusercontent.com/1813435/66663407-b154b680-ec18-11e9-812a-564e85e379de.png">

Without CoBlocks activated: 
<img width="1117" alt="correct-no-coblocks" src="https://user-images.githubusercontent.com/1813435/66663434-bdd90f00-ec18-11e9-8ed5-86fcb649bf74.png">

**Expected behavior**
The existing formatting controls are present, as well as our custom Uppercase control, located in src/formats/uppercase/index.js

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.2.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any) 6.4

**Comment by richtabor** [comment]
Could be related to our `src/formats/`, or perhaps `formattingControls` that we're using on our blocks. I'm not 100% sure.

**Comment by jrtashjian** [comment]
If you disable the following imports from the src/blocks.js file:

```
// import './formats/';
// import * as clickToTweet from './blocks/click-to-tweet';
```

You will no longer seeing the issue. However, it only works if you disable both of those files (not 
just one or the other). Not sure exactly what is causing it yet.

![image](https://user-images.githubusercontent.com/375788/66669453-90469280-ec25-11e9-823a-0bb6330eccd9.png)

**Comment by EvanHerman** [comment]
Adding the following to the top of src/blocks/click-to-tweet/index.js, and doing `// import './formats/';` gets things running:
`import * from '@wordpress/rich-text';`

Although from my testing it looks like `registerFormatType()` removes any default core format types in favor of our new custom one. I can't get the new one appended/prepended.

**Comment by jrtashjian** [comment]
Figured out the root issue here. Had to do with missing dependencies in `wp_register_script`. For some reason setting the `in_footer` param to `true` was messing with the script loading order which was causing our formats to overwrite the existing ones. Setting `in_footer` to `false` and  adding `wp-editor` and `wp-rich-text` as dependencies solved it.

This feels like a bug in Core because I'm not understanding why the registered block types would be removed when ours is registered.
