### ISSUE TITLE
Hyperlinks getting removed form pictures when editing the Masonry Gallery

### ISSUE THREAD

**Issue by guicmazeredo** [godaddy/coblocks#983]
**Describe the bug**
When editing a Masonry gallery to add a new picture, the hyperlinks that were set for the pics that were in the gallery get removed once the new picture is added. 

**To Reproduce**

1. Add a Masonry Gallery to a page or post.
2. Add a few images to the gallery.
3. Click on one of the images and select **Custom URL** under the **Link settings** tab. Then add URL to one or more pics.
4. Then, click on the **Edit** button on the gallery toolbar and add an image to the gallery. 
5. Check the images that were in the gallery already and notice that the URLs set in the previous step are gone.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
WordPress 5.2.3

**Comment by EvanHerman** [comment]
@guicmazeredo 

Great catch - You're right. I'm able to consistently reproduce this. This is an issue regardless of when the gallery is edited. If you create a masonry gallery, and come back 3 weeks later to add another image, all of the URLs would be wiped.

This is something we need to investigate.
